/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class AddedQueueItem {
    /**
     * The queue item id that was added or the existing one if an item already exists in this queue with
     * the same parameters
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<Long> id;

    /**
     * The key added to the queue
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    private Optional<String> key;

    @JsonCreator
    public AddedQueueItem(
            @JsonProperty("id") Optional<Long> id,
            @JsonProperty("key") Optional<String> key) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(key, "key");
        this.id = id;
        this.key = key;
    }
    
    public AddedQueueItem() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * The queue item id that was added or the existing one if an item already exists in this queue with
     * the same parameters
     */
    @JsonIgnore
    public Optional<Long> id() {
        return id;
    }

    /**
     * The key added to the queue
     */
    @JsonIgnore
    public Optional<String> key() {
        return key;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The queue item id that was added or the existing one if an item already exists in this queue with
     * the same parameters
     */
    public AddedQueueItem withId(long id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }


    /**
     * The queue item id that was added or the existing one if an item already exists in this queue with
     * the same parameters
     */
    public AddedQueueItem withId(Optional<Long> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * The key added to the queue
     */
    public AddedQueueItem withKey(String key) {
        Utils.checkNotNull(key, "key");
        this.key = Optional.ofNullable(key);
        return this;
    }


    /**
     * The key added to the queue
     */
    public AddedQueueItem withKey(Optional<String> key) {
        Utils.checkNotNull(key, "key");
        this.key = key;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AddedQueueItem other = (AddedQueueItem) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.key, other.key);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, key);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AddedQueueItem.class,
                "id", id,
                "key", key);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Long> id = Optional.empty();

        private Optional<String> key = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The queue item id that was added or the existing one if an item already exists in this queue with
         * the same parameters
         */
        public Builder id(long id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * The queue item id that was added or the existing one if an item already exists in this queue with
         * the same parameters
         */
        public Builder id(Optional<Long> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        /**
         * The key added to the queue
         */
        public Builder key(String key) {
            Utils.checkNotNull(key, "key");
            this.key = Optional.ofNullable(key);
            return this;
        }

        /**
         * The key added to the queue
         */
        public Builder key(Optional<String> key) {
            Utils.checkNotNull(key, "key");
            this.key = key;
            return this;
        }

        public AddedQueueItem build() {

            return new AddedQueueItem(
                id, key);
        }

    }
}
