/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum AllowSync3 {
    ZERO("0"),
    ONE("1");

    @JsonValue
    private final String value;

    AllowSync3(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AllowSync3> fromValue(String value) {
        for (AllowSync3 o: AllowSync3.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

