/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class AuthKeysResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("keys")
    private Optional<? extends List<Keys>> keys;

    @JsonCreator
    public AuthKeysResponse(
            @JsonProperty("keys") Optional<? extends List<Keys>> keys) {
        Utils.checkNotNull(keys, "keys");
        this.keys = keys;
    }
    
    public AuthKeysResponse() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Keys>> keys() {
        return (Optional<List<Keys>>) keys;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AuthKeysResponse withKeys(List<Keys> keys) {
        Utils.checkNotNull(keys, "keys");
        this.keys = Optional.ofNullable(keys);
        return this;
    }


    public AuthKeysResponse withKeys(Optional<? extends List<Keys>> keys) {
        Utils.checkNotNull(keys, "keys");
        this.keys = keys;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthKeysResponse other = (AuthKeysResponse) o;
        return 
            Utils.enhancedDeepEquals(this.keys, other.keys);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            keys);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthKeysResponse.class,
                "keys", keys);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<Keys>> keys = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder keys(List<Keys> keys) {
            Utils.checkNotNull(keys, "keys");
            this.keys = Optional.ofNullable(keys);
            return this;
        }

        public Builder keys(Optional<? extends List<Keys>> keys) {
            Utils.checkNotNull(keys, "keys");
            this.keys = keys;
            return this;
        }

        public AuthKeysResponse build() {

            return new AuthKeysResponse(
                keys);
        }

    }
}
