/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class Lineup {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private Optional<String> title;

    /**
     * The type of this object (`lineup` in this case)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<String> type;

    /**
     * Lineup identifier.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifier")
    private Optional<String> identifier;

    /**
     * API key for this lineup.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    private Optional<String> key;

    /**
     * - `-1`: N/A
     * - `0`: Over the air
     * - `1`: Cable
     * - `2`: Satellite
     * - `3`: IPTV
     * - `4`: Virtual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lineupType")
    private Optional<? extends LineupType> lineupType;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("location")
    private Optional<String> location;

    /**
     * The uuid of this lineup
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uuid")
    private Optional<String> uuid;

    @JsonCreator
    public Lineup(
            @JsonProperty("title") Optional<String> title,
            @JsonProperty("type") Optional<String> type,
            @JsonProperty("identifier") Optional<String> identifier,
            @JsonProperty("key") Optional<String> key,
            @JsonProperty("lineupType") Optional<? extends LineupType> lineupType,
            @JsonProperty("location") Optional<String> location,
            @JsonProperty("uuid") Optional<String> uuid) {
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(identifier, "identifier");
        Utils.checkNotNull(key, "key");
        Utils.checkNotNull(lineupType, "lineupType");
        Utils.checkNotNull(location, "location");
        Utils.checkNotNull(uuid, "uuid");
        this.title = title;
        this.type = type;
        this.identifier = identifier;
        this.key = key;
        this.lineupType = lineupType;
        this.location = location;
        this.uuid = uuid;
    }
    
    public Lineup() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    @JsonIgnore
    public Optional<String> title() {
        return title;
    }

    /**
     * The type of this object (`lineup` in this case)
     */
    @JsonIgnore
    public Optional<String> type() {
        return type;
    }

    /**
     * Lineup identifier.
     */
    @JsonIgnore
    public Optional<String> identifier() {
        return identifier;
    }

    /**
     * API key for this lineup.
     */
    @JsonIgnore
    public Optional<String> key() {
        return key;
    }

    /**
     * - `-1`: N/A
     * - `0`: Over the air
     * - `1`: Cable
     * - `2`: Satellite
     * - `3`: IPTV
     * - `4`: Virtual
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<LineupType> lineupType() {
        return (Optional<LineupType>) lineupType;
    }

    @JsonIgnore
    public Optional<String> location() {
        return location;
    }

    /**
     * The uuid of this lineup
     */
    @JsonIgnore
    public Optional<String> uuid() {
        return uuid;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Lineup withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = Optional.ofNullable(title);
        return this;
    }


    public Lineup withTitle(Optional<String> title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * The type of this object (`lineup` in this case)
     */
    public Lineup withType(String type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    /**
     * The type of this object (`lineup` in this case)
     */
    public Lineup withType(Optional<String> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * Lineup identifier.
     */
    public Lineup withIdentifier(String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = Optional.ofNullable(identifier);
        return this;
    }


    /**
     * Lineup identifier.
     */
    public Lineup withIdentifier(Optional<String> identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
        return this;
    }

    /**
     * API key for this lineup.
     */
    public Lineup withKey(String key) {
        Utils.checkNotNull(key, "key");
        this.key = Optional.ofNullable(key);
        return this;
    }


    /**
     * API key for this lineup.
     */
    public Lineup withKey(Optional<String> key) {
        Utils.checkNotNull(key, "key");
        this.key = key;
        return this;
    }

    /**
     * - `-1`: N/A
     * - `0`: Over the air
     * - `1`: Cable
     * - `2`: Satellite
     * - `3`: IPTV
     * - `4`: Virtual
     */
    public Lineup withLineupType(LineupType lineupType) {
        Utils.checkNotNull(lineupType, "lineupType");
        this.lineupType = Optional.ofNullable(lineupType);
        return this;
    }


    /**
     * - `-1`: N/A
     * - `0`: Over the air
     * - `1`: Cable
     * - `2`: Satellite
     * - `3`: IPTV
     * - `4`: Virtual
     */
    public Lineup withLineupType(Optional<? extends LineupType> lineupType) {
        Utils.checkNotNull(lineupType, "lineupType");
        this.lineupType = lineupType;
        return this;
    }

    public Lineup withLocation(String location) {
        Utils.checkNotNull(location, "location");
        this.location = Optional.ofNullable(location);
        return this;
    }


    public Lineup withLocation(Optional<String> location) {
        Utils.checkNotNull(location, "location");
        this.location = location;
        return this;
    }

    /**
     * The uuid of this lineup
     */
    public Lineup withUuid(String uuid) {
        Utils.checkNotNull(uuid, "uuid");
        this.uuid = Optional.ofNullable(uuid);
        return this;
    }


    /**
     * The uuid of this lineup
     */
    public Lineup withUuid(Optional<String> uuid) {
        Utils.checkNotNull(uuid, "uuid");
        this.uuid = uuid;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Lineup other = (Lineup) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.lineupType, other.lineupType) &&
            Utils.enhancedDeepEquals(this.location, other.location) &&
            Utils.enhancedDeepEquals(this.uuid, other.uuid);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, type, identifier,
            key, lineupType, location,
            uuid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Lineup.class,
                "title", title,
                "type", type,
                "identifier", identifier,
                "key", key,
                "lineupType", lineupType,
                "location", location,
                "uuid", uuid);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> title = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Optional<String> identifier = Optional.empty();

        private Optional<String> key = Optional.empty();

        private Optional<? extends LineupType> lineupType = Optional.empty();

        private Optional<String> location = Optional.empty();

        private Optional<String> uuid = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = Optional.ofNullable(title);
            return this;
        }

        public Builder title(Optional<String> title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }


        /**
         * The type of this object (`lineup` in this case)
         */
        public Builder type(String type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * The type of this object (`lineup` in this case)
         */
        public Builder type(Optional<String> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        /**
         * Lineup identifier.
         */
        public Builder identifier(String identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = Optional.ofNullable(identifier);
            return this;
        }

        /**
         * Lineup identifier.
         */
        public Builder identifier(Optional<String> identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = identifier;
            return this;
        }


        /**
         * API key for this lineup.
         */
        public Builder key(String key) {
            Utils.checkNotNull(key, "key");
            this.key = Optional.ofNullable(key);
            return this;
        }

        /**
         * API key for this lineup.
         */
        public Builder key(Optional<String> key) {
            Utils.checkNotNull(key, "key");
            this.key = key;
            return this;
        }


        /**
         * - `-1`: N/A
         * - `0`: Over the air
         * - `1`: Cable
         * - `2`: Satellite
         * - `3`: IPTV
         * - `4`: Virtual
         */
        public Builder lineupType(LineupType lineupType) {
            Utils.checkNotNull(lineupType, "lineupType");
            this.lineupType = Optional.ofNullable(lineupType);
            return this;
        }

        /**
         * - `-1`: N/A
         * - `0`: Over the air
         * - `1`: Cable
         * - `2`: Satellite
         * - `3`: IPTV
         * - `4`: Virtual
         */
        public Builder lineupType(Optional<? extends LineupType> lineupType) {
            Utils.checkNotNull(lineupType, "lineupType");
            this.lineupType = lineupType;
            return this;
        }


        public Builder location(String location) {
            Utils.checkNotNull(location, "location");
            this.location = Optional.ofNullable(location);
            return this;
        }

        public Builder location(Optional<String> location) {
            Utils.checkNotNull(location, "location");
            this.location = location;
            return this;
        }


        /**
         * The uuid of this lineup
         */
        public Builder uuid(String uuid) {
            Utils.checkNotNull(uuid, "uuid");
            this.uuid = Optional.ofNullable(uuid);
            return this;
        }

        /**
         * The uuid of this lineup
         */
        public Builder uuid(Optional<String> uuid) {
            Utils.checkNotNull(uuid, "uuid");
            this.uuid = uuid;
            return this;
        }

        public Lineup build() {

            return new Lineup(
                title, type, identifier,
                key, lineupType, location,
                uuid);
        }

    }
}
