/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class MediaContainerWithDirectory1 {

    private Optional<? extends MediaContainerWithDirectoryMediaContainer1> mediaContainer;

    @JsonCreator
    public MediaContainerWithDirectory1(
            Optional<? extends MediaContainerWithDirectoryMediaContainer1> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
    }
    
    public MediaContainerWithDirectory1() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<MediaContainerWithDirectoryMediaContainer1> mediaContainer() {
        return (Optional<MediaContainerWithDirectoryMediaContainer1>) mediaContainer;
    }

    public static Builder builder() {
        return new Builder();
    }


    public MediaContainerWithDirectory1 withMediaContainer(MediaContainerWithDirectoryMediaContainer1 mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = Optional.ofNullable(mediaContainer);
        return this;
    }


    public MediaContainerWithDirectory1 withMediaContainer(Optional<? extends MediaContainerWithDirectoryMediaContainer1> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MediaContainerWithDirectory1 other = (MediaContainerWithDirectory1) o;
        return 
            Utils.enhancedDeepEquals(this.mediaContainer, other.mediaContainer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mediaContainer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MediaContainerWithDirectory1.class,
                "mediaContainer", mediaContainer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends MediaContainerWithDirectoryMediaContainer1> mediaContainer = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder mediaContainer(MediaContainerWithDirectoryMediaContainer1 mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = Optional.ofNullable(mediaContainer);
            return this;
        }

        public Builder mediaContainer(Optional<? extends MediaContainerWithDirectoryMediaContainer1> mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = mediaContainer;
            return this;
        }

        public MediaContainerWithDirectory1 build() {

            return new MediaContainerWithDirectory1(
                mediaContainer);
        }

    }
}
