/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public enum MediaContainerWithDecisionOptimizedForStreaming {
    ZERO(0),
    ONE(1);

    @JsonValue
    private final int value;

    MediaContainerWithDecisionOptimizedForStreaming(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
    
    public static Optional<MediaContainerWithDecisionOptimizedForStreaming> fromValue(int value) {
        for (MediaContainerWithDecisionOptimizedForStreaming o: MediaContainerWithDecisionOptimizedForStreaming.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

