/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class MediaContainerWithStatus {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("MediaContainer")
    private Optional<? extends MediaContainerWithStatusMediaContainer> mediaContainer;

    @JsonCreator
    public MediaContainerWithStatus(
            @JsonProperty("MediaContainer") Optional<? extends MediaContainerWithStatusMediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
    }
    
    public MediaContainerWithStatus() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<MediaContainerWithStatusMediaContainer> mediaContainer() {
        return (Optional<MediaContainerWithStatusMediaContainer>) mediaContainer;
    }

    public static Builder builder() {
        return new Builder();
    }


    public MediaContainerWithStatus withMediaContainer(MediaContainerWithStatusMediaContainer mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = Optional.ofNullable(mediaContainer);
        return this;
    }


    public MediaContainerWithStatus withMediaContainer(Optional<? extends MediaContainerWithStatusMediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MediaContainerWithStatus other = (MediaContainerWithStatus) o;
        return 
            Utils.enhancedDeepEquals(this.mediaContainer, other.mediaContainer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mediaContainer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MediaContainerWithStatus.class,
                "mediaContainer", mediaContainer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends MediaContainerWithStatusMediaContainer> mediaContainer = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder mediaContainer(MediaContainerWithStatusMediaContainer mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = Optional.ofNullable(mediaContainer);
            return this;
        }

        public Builder mediaContainer(Optional<? extends MediaContainerWithStatusMediaContainer> mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = mediaContainer;
            return this;
        }

        public MediaContainerWithStatus build() {

            return new MediaContainerWithStatus(
                mediaContainer);
        }

    }
}
