/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * PlaySessionStateNotification
 * 
 * <p>Real-time playback state change notification
 */
public class PlaySessionStateNotification {

    private Optional<String> controllable;


    private Optional<String> guid;


    private Optional<String> key;


    private Optional<Long> playQueueID;


    private Optional<Long> playQueueItemID;


    private Optional<String> ratingKey;


    private Optional<String> sessionKey;


    private Optional<? extends State> state;


    private Optional<String> transcodeSession;


    private Optional<String> url;


    private Optional<Long> viewOffset;

    @JsonCreator
    public PlaySessionStateNotification(
            Optional<String> controllable,
            Optional<String> guid,
            Optional<String> key,
            Optional<Long> playQueueID,
            Optional<Long> playQueueItemID,
            Optional<String> ratingKey,
            Optional<String> sessionKey,
            Optional<? extends State> state,
            Optional<String> transcodeSession,
            Optional<String> url,
            Optional<Long> viewOffset) {
        Utils.checkNotNull(controllable, "controllable");
        Utils.checkNotNull(guid, "guid");
        Utils.checkNotNull(key, "key");
        Utils.checkNotNull(playQueueID, "playQueueID");
        Utils.checkNotNull(playQueueItemID, "playQueueItemID");
        Utils.checkNotNull(ratingKey, "ratingKey");
        Utils.checkNotNull(sessionKey, "sessionKey");
        Utils.checkNotNull(state, "state");
        Utils.checkNotNull(transcodeSession, "transcodeSession");
        Utils.checkNotNull(url, "url");
        Utils.checkNotNull(viewOffset, "viewOffset");
        this.controllable = controllable;
        this.guid = guid;
        this.key = key;
        this.playQueueID = playQueueID;
        this.playQueueItemID = playQueueItemID;
        this.ratingKey = ratingKey;
        this.sessionKey = sessionKey;
        this.state = state;
        this.transcodeSession = transcodeSession;
        this.url = url;
        this.viewOffset = viewOffset;
    }
    
    public PlaySessionStateNotification() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<String> controllable() {
        return controllable;
    }

    @JsonIgnore
    public Optional<String> guid() {
        return guid;
    }

    @JsonIgnore
    public Optional<String> key() {
        return key;
    }

    @JsonIgnore
    public Optional<Long> playQueueID() {
        return playQueueID;
    }

    @JsonIgnore
    public Optional<Long> playQueueItemID() {
        return playQueueItemID;
    }

    @JsonIgnore
    public Optional<String> ratingKey() {
        return ratingKey;
    }

    @JsonIgnore
    public Optional<String> sessionKey() {
        return sessionKey;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<State> state() {
        return (Optional<State>) state;
    }

    @JsonIgnore
    public Optional<String> transcodeSession() {
        return transcodeSession;
    }

    @JsonIgnore
    public Optional<String> url() {
        return url;
    }

    @JsonIgnore
    public Optional<Long> viewOffset() {
        return viewOffset;
    }

    public static Builder builder() {
        return new Builder();
    }


    public PlaySessionStateNotification withControllable(String controllable) {
        Utils.checkNotNull(controllable, "controllable");
        this.controllable = Optional.ofNullable(controllable);
        return this;
    }


    public PlaySessionStateNotification withControllable(Optional<String> controllable) {
        Utils.checkNotNull(controllable, "controllable");
        this.controllable = controllable;
        return this;
    }

    public PlaySessionStateNotification withGuid(String guid) {
        Utils.checkNotNull(guid, "guid");
        this.guid = Optional.ofNullable(guid);
        return this;
    }


    public PlaySessionStateNotification withGuid(Optional<String> guid) {
        Utils.checkNotNull(guid, "guid");
        this.guid = guid;
        return this;
    }

    public PlaySessionStateNotification withKey(String key) {
        Utils.checkNotNull(key, "key");
        this.key = Optional.ofNullable(key);
        return this;
    }


    public PlaySessionStateNotification withKey(Optional<String> key) {
        Utils.checkNotNull(key, "key");
        this.key = key;
        return this;
    }

    public PlaySessionStateNotification withPlayQueueID(long playQueueID) {
        Utils.checkNotNull(playQueueID, "playQueueID");
        this.playQueueID = Optional.ofNullable(playQueueID);
        return this;
    }


    public PlaySessionStateNotification withPlayQueueID(Optional<Long> playQueueID) {
        Utils.checkNotNull(playQueueID, "playQueueID");
        this.playQueueID = playQueueID;
        return this;
    }

    public PlaySessionStateNotification withPlayQueueItemID(long playQueueItemID) {
        Utils.checkNotNull(playQueueItemID, "playQueueItemID");
        this.playQueueItemID = Optional.ofNullable(playQueueItemID);
        return this;
    }


    public PlaySessionStateNotification withPlayQueueItemID(Optional<Long> playQueueItemID) {
        Utils.checkNotNull(playQueueItemID, "playQueueItemID");
        this.playQueueItemID = playQueueItemID;
        return this;
    }

    public PlaySessionStateNotification withRatingKey(String ratingKey) {
        Utils.checkNotNull(ratingKey, "ratingKey");
        this.ratingKey = Optional.ofNullable(ratingKey);
        return this;
    }


    public PlaySessionStateNotification withRatingKey(Optional<String> ratingKey) {
        Utils.checkNotNull(ratingKey, "ratingKey");
        this.ratingKey = ratingKey;
        return this;
    }

    public PlaySessionStateNotification withSessionKey(String sessionKey) {
        Utils.checkNotNull(sessionKey, "sessionKey");
        this.sessionKey = Optional.ofNullable(sessionKey);
        return this;
    }


    public PlaySessionStateNotification withSessionKey(Optional<String> sessionKey) {
        Utils.checkNotNull(sessionKey, "sessionKey");
        this.sessionKey = sessionKey;
        return this;
    }

    public PlaySessionStateNotification withState(State state) {
        Utils.checkNotNull(state, "state");
        this.state = Optional.ofNullable(state);
        return this;
    }


    public PlaySessionStateNotification withState(Optional<? extends State> state) {
        Utils.checkNotNull(state, "state");
        this.state = state;
        return this;
    }

    public PlaySessionStateNotification withTranscodeSession(String transcodeSession) {
        Utils.checkNotNull(transcodeSession, "transcodeSession");
        this.transcodeSession = Optional.ofNullable(transcodeSession);
        return this;
    }


    public PlaySessionStateNotification withTranscodeSession(Optional<String> transcodeSession) {
        Utils.checkNotNull(transcodeSession, "transcodeSession");
        this.transcodeSession = transcodeSession;
        return this;
    }

    public PlaySessionStateNotification withUrl(String url) {
        Utils.checkNotNull(url, "url");
        this.url = Optional.ofNullable(url);
        return this;
    }


    public PlaySessionStateNotification withUrl(Optional<String> url) {
        Utils.checkNotNull(url, "url");
        this.url = url;
        return this;
    }

    public PlaySessionStateNotification withViewOffset(long viewOffset) {
        Utils.checkNotNull(viewOffset, "viewOffset");
        this.viewOffset = Optional.ofNullable(viewOffset);
        return this;
    }


    public PlaySessionStateNotification withViewOffset(Optional<Long> viewOffset) {
        Utils.checkNotNull(viewOffset, "viewOffset");
        this.viewOffset = viewOffset;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlaySessionStateNotification other = (PlaySessionStateNotification) o;
        return 
            Utils.enhancedDeepEquals(this.controllable, other.controllable) &&
            Utils.enhancedDeepEquals(this.guid, other.guid) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.playQueueID, other.playQueueID) &&
            Utils.enhancedDeepEquals(this.playQueueItemID, other.playQueueItemID) &&
            Utils.enhancedDeepEquals(this.ratingKey, other.ratingKey) &&
            Utils.enhancedDeepEquals(this.sessionKey, other.sessionKey) &&
            Utils.enhancedDeepEquals(this.state, other.state) &&
            Utils.enhancedDeepEquals(this.transcodeSession, other.transcodeSession) &&
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.viewOffset, other.viewOffset);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            controllable, guid, key,
            playQueueID, playQueueItemID, ratingKey,
            sessionKey, state, transcodeSession,
            url, viewOffset);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlaySessionStateNotification.class,
                "controllable", controllable,
                "guid", guid,
                "key", key,
                "playQueueID", playQueueID,
                "playQueueItemID", playQueueItemID,
                "ratingKey", ratingKey,
                "sessionKey", sessionKey,
                "state", state,
                "transcodeSession", transcodeSession,
                "url", url,
                "viewOffset", viewOffset);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> controllable = Optional.empty();

        private Optional<String> guid = Optional.empty();

        private Optional<String> key = Optional.empty();

        private Optional<Long> playQueueID = Optional.empty();

        private Optional<Long> playQueueItemID = Optional.empty();

        private Optional<String> ratingKey = Optional.empty();

        private Optional<String> sessionKey = Optional.empty();

        private Optional<? extends State> state = Optional.empty();

        private Optional<String> transcodeSession = Optional.empty();

        private Optional<String> url = Optional.empty();

        private Optional<Long> viewOffset = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder controllable(String controllable) {
            Utils.checkNotNull(controllable, "controllable");
            this.controllable = Optional.ofNullable(controllable);
            return this;
        }

        public Builder controllable(Optional<String> controllable) {
            Utils.checkNotNull(controllable, "controllable");
            this.controllable = controllable;
            return this;
        }


        public Builder guid(String guid) {
            Utils.checkNotNull(guid, "guid");
            this.guid = Optional.ofNullable(guid);
            return this;
        }

        public Builder guid(Optional<String> guid) {
            Utils.checkNotNull(guid, "guid");
            this.guid = guid;
            return this;
        }


        public Builder key(String key) {
            Utils.checkNotNull(key, "key");
            this.key = Optional.ofNullable(key);
            return this;
        }

        public Builder key(Optional<String> key) {
            Utils.checkNotNull(key, "key");
            this.key = key;
            return this;
        }


        public Builder playQueueID(long playQueueID) {
            Utils.checkNotNull(playQueueID, "playQueueID");
            this.playQueueID = Optional.ofNullable(playQueueID);
            return this;
        }

        public Builder playQueueID(Optional<Long> playQueueID) {
            Utils.checkNotNull(playQueueID, "playQueueID");
            this.playQueueID = playQueueID;
            return this;
        }


        public Builder playQueueItemID(long playQueueItemID) {
            Utils.checkNotNull(playQueueItemID, "playQueueItemID");
            this.playQueueItemID = Optional.ofNullable(playQueueItemID);
            return this;
        }

        public Builder playQueueItemID(Optional<Long> playQueueItemID) {
            Utils.checkNotNull(playQueueItemID, "playQueueItemID");
            this.playQueueItemID = playQueueItemID;
            return this;
        }


        public Builder ratingKey(String ratingKey) {
            Utils.checkNotNull(ratingKey, "ratingKey");
            this.ratingKey = Optional.ofNullable(ratingKey);
            return this;
        }

        public Builder ratingKey(Optional<String> ratingKey) {
            Utils.checkNotNull(ratingKey, "ratingKey");
            this.ratingKey = ratingKey;
            return this;
        }


        public Builder sessionKey(String sessionKey) {
            Utils.checkNotNull(sessionKey, "sessionKey");
            this.sessionKey = Optional.ofNullable(sessionKey);
            return this;
        }

        public Builder sessionKey(Optional<String> sessionKey) {
            Utils.checkNotNull(sessionKey, "sessionKey");
            this.sessionKey = sessionKey;
            return this;
        }


        public Builder state(State state) {
            Utils.checkNotNull(state, "state");
            this.state = Optional.ofNullable(state);
            return this;
        }

        public Builder state(Optional<? extends State> state) {
            Utils.checkNotNull(state, "state");
            this.state = state;
            return this;
        }


        public Builder transcodeSession(String transcodeSession) {
            Utils.checkNotNull(transcodeSession, "transcodeSession");
            this.transcodeSession = Optional.ofNullable(transcodeSession);
            return this;
        }

        public Builder transcodeSession(Optional<String> transcodeSession) {
            Utils.checkNotNull(transcodeSession, "transcodeSession");
            this.transcodeSession = transcodeSession;
            return this;
        }


        public Builder url(String url) {
            Utils.checkNotNull(url, "url");
            this.url = Optional.ofNullable(url);
            return this;
        }

        public Builder url(Optional<String> url) {
            Utils.checkNotNull(url, "url");
            this.url = url;
            return this;
        }


        public Builder viewOffset(long viewOffset) {
            Utils.checkNotNull(viewOffset, "viewOffset");
            this.viewOffset = Optional.ofNullable(viewOffset);
            return this;
        }

        public Builder viewOffset(Optional<Long> viewOffset) {
            Utils.checkNotNull(viewOffset, "viewOffset");
            this.viewOffset = viewOffset;
            return this;
        }

        public PlaySessionStateNotification build() {

            return new PlaySessionStateNotification(
                controllable, guid, key,
                playQueueID, playQueueItemID, ratingKey,
                sessionKey, state, transcodeSession,
                url, viewOffset);
        }

    }
}
