/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ReachabilityNotification
 * 
 * <p>Server reachability status change notification
 */
public class ReachabilityNotification {

    private Optional<String> status;

    @JsonCreator
    public ReachabilityNotification(
            Optional<String> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
    }
    
    public ReachabilityNotification() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<String> status() {
        return status;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ReachabilityNotification withStatus(String status) {
        Utils.checkNotNull(status, "status");
        this.status = Optional.ofNullable(status);
        return this;
    }


    public ReachabilityNotification withStatus(Optional<String> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReachabilityNotification other = (ReachabilityNotification) o;
        return 
            Utils.enhancedDeepEquals(this.status, other.status);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            status);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ReachabilityNotification.class,
                "status", status);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> status = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder status(String status) {
            Utils.checkNotNull(status, "status");
            this.status = Optional.ofNullable(status);
            return this;
        }

        public Builder status(Optional<String> status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }

        public ReachabilityNotification build() {

            return new ReachabilityNotification(
                status);
        }

    }
}
