/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class UserPlexAccountStatus {

    public static final UserPlexAccountStatus Online = new UserPlexAccountStatus("online");
    public static final UserPlexAccountStatus Offline = new UserPlexAccountStatus("offline");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, UserPlexAccountStatus> values = createValuesMap();
    private static final Map<String, UserPlexAccountStatusEnum> enums = createEnumsMap();

    private final String value;

    private UserPlexAccountStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a UserPlexAccountStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as UserPlexAccountStatus
     */ 
    @JsonCreator
    public static UserPlexAccountStatus of(String value) {
        synchronized (UserPlexAccountStatus.class) {
            return values.computeIfAbsent(value, v -> new UserPlexAccountStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<UserPlexAccountStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UserPlexAccountStatus other = (UserPlexAccountStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "UserPlexAccountStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static UserPlexAccountStatus[] values() {
        synchronized (UserPlexAccountStatus.class) {
            return values.values().toArray(new UserPlexAccountStatus[] {});
        }
    }

    private static final Map<String, UserPlexAccountStatus> createValuesMap() {
        Map<String, UserPlexAccountStatus> map = new LinkedHashMap<>();
        map.put("online", Online);
        map.put("offline", Offline);
        return map;
    }

    private static final Map<String, UserPlexAccountStatusEnum> createEnumsMap() {
        Map<String, UserPlexAccountStatusEnum> map = new HashMap<>();
        map.put("online", UserPlexAccountStatusEnum.Online);
        map.put("offline", UserPlexAccountStatusEnum.Offline);
        return map;
    }
    
    
    public enum UserPlexAccountStatusEnum {

        Online("online"),
        Offline("offline"),;

        private final String value;

        private UserPlexAccountStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

