/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.plexapi.sdk.models.shared.ServerAccessTokensResponse;
import dev.plexapi.sdk.utils.AsyncResponse;
import dev.plexapi.sdk.utils.Blob;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetServerAccessTokensResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * OK
     */
    private Optional<? extends ServerAccessTokensResponse> serverAccessTokensResponse;

    @JsonCreator
    public GetServerAccessTokensResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends ServerAccessTokensResponse> serverAccessTokensResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(serverAccessTokensResponse, "serverAccessTokensResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.serverAccessTokensResponse = serverAccessTokensResponse;
    }
    
    public GetServerAccessTokensResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ServerAccessTokensResponse> serverAccessTokensResponse() {
        return (Optional<ServerAccessTokensResponse>) serverAccessTokensResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetServerAccessTokensResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetServerAccessTokensResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetServerAccessTokensResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public GetServerAccessTokensResponse withServerAccessTokensResponse(ServerAccessTokensResponse serverAccessTokensResponse) {
        Utils.checkNotNull(serverAccessTokensResponse, "serverAccessTokensResponse");
        this.serverAccessTokensResponse = Optional.ofNullable(serverAccessTokensResponse);
        return this;
    }


    /**
     * OK
     */
    public GetServerAccessTokensResponse withServerAccessTokensResponse(Optional<? extends ServerAccessTokensResponse> serverAccessTokensResponse) {
        Utils.checkNotNull(serverAccessTokensResponse, "serverAccessTokensResponse");
        this.serverAccessTokensResponse = serverAccessTokensResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetServerAccessTokensResponse other = (GetServerAccessTokensResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.serverAccessTokensResponse, other.serverAccessTokensResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            serverAccessTokensResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetServerAccessTokensResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "serverAccessTokensResponse", serverAccessTokensResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends ServerAccessTokensResponse> serverAccessTokensResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * OK
         */
        public Builder serverAccessTokensResponse(ServerAccessTokensResponse serverAccessTokensResponse) {
            Utils.checkNotNull(serverAccessTokensResponse, "serverAccessTokensResponse");
            this.serverAccessTokensResponse = Optional.ofNullable(serverAccessTokensResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder serverAccessTokensResponse(Optional<? extends ServerAccessTokensResponse> serverAccessTokensResponse) {
            Utils.checkNotNull(serverAccessTokensResponse, "serverAccessTokensResponse");
            this.serverAccessTokensResponse = serverAccessTokensResponse;
            return this;
        }

        public GetServerAccessTokensResponse build() {

            return new GetServerAccessTokensResponse(
                contentType, statusCode, rawResponse,
                serverAccessTokensResponse);
        }

    }
}
