/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestlessOperation;
import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.models.operations.DeleteHistoryRequest;
import dev.plexapi.sdk.models.operations.GetHistoryItemRequest;
import dev.plexapi.sdk.models.operations.ListPlaybackHistoryRequest;
import dev.plexapi.sdk.models.operations.TerminateSessionRequest;
import dev.plexapi.sdk.models.operations.async.DeleteHistoryRequestBuilder;
import dev.plexapi.sdk.models.operations.async.DeleteHistoryResponse;
import dev.plexapi.sdk.models.operations.async.GetBackgroundTasksRequestBuilder;
import dev.plexapi.sdk.models.operations.async.GetBackgroundTasksResponse;
import dev.plexapi.sdk.models.operations.async.GetHistoryItemRequestBuilder;
import dev.plexapi.sdk.models.operations.async.GetHistoryItemResponse;
import dev.plexapi.sdk.models.operations.async.ListPlaybackHistoryRequestBuilder;
import dev.plexapi.sdk.models.operations.async.ListPlaybackHistoryResponse;
import dev.plexapi.sdk.models.operations.async.ListSessionsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.ListSessionsResponse;
import dev.plexapi.sdk.models.operations.async.TerminateSessionRequestBuilder;
import dev.plexapi.sdk.models.operations.async.TerminateSessionResponse;
import dev.plexapi.sdk.operations.DeleteHistory;
import dev.plexapi.sdk.operations.GetBackgroundTasks;
import dev.plexapi.sdk.operations.GetHistoryItem;
import dev.plexapi.sdk.operations.ListPlaybackHistory;
import dev.plexapi.sdk.operations.ListSessions;
import dev.plexapi.sdk.operations.TerminateSession;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * The status endpoints give you information about current playbacks, play history, and even
 * terminating sessions.
 */
public class AsyncStatus {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Status syncSDK;

    AsyncStatus(Status syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Status sync() {
        return syncSDK;
    }


    /**
     * List Sessions
     * 
     * <p>List all current playbacks on this server
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public ListSessionsRequestBuilder listSessions() {
        return new ListSessionsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Sessions
     * 
     * <p>List all current playbacks on this server
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return {@code CompletableFuture<ListSessionsResponse>} - The async response
     */
    public CompletableFuture<ListSessionsResponse> listSessionsDirect() {
        return listSessions(Optional.empty());
    }

    /**
     * List Sessions
     * 
     * <p>List all current playbacks on this server
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param options additional options
     * @return {@code CompletableFuture<ListSessionsResponse>} - The async response
     */
    public CompletableFuture<ListSessionsResponse> listSessions(Optional<Options> options) {
        AsyncRequestlessOperation<ListSessionsResponse> operation
            = new ListSessions.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get background tasks
     * 
     * <p>Get the list of all background tasks
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public GetBackgroundTasksRequestBuilder getBackgroundTasks() {
        return new GetBackgroundTasksRequestBuilder(sdkConfiguration);
    }

    /**
     * Get background tasks
     * 
     * <p>Get the list of all background tasks
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return {@code CompletableFuture<GetBackgroundTasksResponse>} - The async response
     */
    public CompletableFuture<GetBackgroundTasksResponse> getBackgroundTasksDirect() {
        return getBackgroundTasks(Optional.empty());
    }

    /**
     * Get background tasks
     * 
     * <p>Get the list of all background tasks
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param options additional options
     * @return {@code CompletableFuture<GetBackgroundTasksResponse>} - The async response
     */
    public CompletableFuture<GetBackgroundTasksResponse> getBackgroundTasks(Optional<Options> options) {
        AsyncRequestlessOperation<GetBackgroundTasksResponse> operation
            = new GetBackgroundTasks.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * List Playback History
     * 
     * <p>List all playback history (Admin can see all users, others can only see their own).
     * Pagination should be used on this endpoint. Additionally this endpoint supports `includeFields`,
     * `excludeFields`, `includeElements`, and `excludeElements` parameters.
     * 
     * @return The async call builder
     */
    public ListPlaybackHistoryRequestBuilder listPlaybackHistory() {
        return new ListPlaybackHistoryRequestBuilder(sdkConfiguration);
    }

    /**
     * List Playback History
     * 
     * <p>List all playback history (Admin can see all users, others can only see their own).
     * Pagination should be used on this endpoint. Additionally this endpoint supports `includeFields`,
     * `excludeFields`, `includeElements`, and `excludeElements` parameters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListPlaybackHistoryResponse>} - The async response
     */
    public CompletableFuture<ListPlaybackHistoryResponse> listPlaybackHistory(ListPlaybackHistoryRequest request) {
        return listPlaybackHistory(request, Optional.empty());
    }

    /**
     * List Playback History
     * 
     * <p>List all playback history (Admin can see all users, others can only see their own).
     * Pagination should be used on this endpoint. Additionally this endpoint supports `includeFields`,
     * `excludeFields`, `includeElements`, and `excludeElements` parameters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ListPlaybackHistoryResponse>} - The async response
     */
    public CompletableFuture<ListPlaybackHistoryResponse> listPlaybackHistory(ListPlaybackHistoryRequest request, Optional<Options> options) {
        AsyncRequestOperation<ListPlaybackHistoryRequest, ListPlaybackHistoryResponse> operation
              = new ListPlaybackHistory.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Terminate a session
     * 
     * <p>Terminate a playback session kicking off the user
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public TerminateSessionRequestBuilder terminateSession() {
        return new TerminateSessionRequestBuilder(sdkConfiguration);
    }

    /**
     * Terminate a session
     * 
     * <p>Terminate a playback session kicking off the user
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<TerminateSessionResponse>} - The async response
     */
    public CompletableFuture<TerminateSessionResponse> terminateSession(TerminateSessionRequest request) {
        return terminateSession(request, Optional.empty());
    }

    /**
     * Terminate a session
     * 
     * <p>Terminate a playback session kicking off the user
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<TerminateSessionResponse>} - The async response
     */
    public CompletableFuture<TerminateSessionResponse> terminateSession(TerminateSessionRequest request, Optional<Options> options) {
        AsyncRequestOperation<TerminateSessionRequest, TerminateSessionResponse> operation
              = new TerminateSession.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete Single History Item
     * 
     * <p>Delete a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public DeleteHistoryRequestBuilder deleteHistory() {
        return new DeleteHistoryRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete Single History Item
     * 
     * <p>Delete a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<DeleteHistoryResponse>} - The async response
     */
    public CompletableFuture<DeleteHistoryResponse> deleteHistory(DeleteHistoryRequest request) {
        return deleteHistory(request, Optional.empty());
    }

    /**
     * Delete Single History Item
     * 
     * <p>Delete a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<DeleteHistoryResponse>} - The async response
     */
    public CompletableFuture<DeleteHistoryResponse> deleteHistory(DeleteHistoryRequest request, Optional<Options> options) {
        AsyncRequestOperation<DeleteHistoryRequest, DeleteHistoryResponse> operation
              = new DeleteHistory.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Single History Item
     * 
     * <p>Get a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public GetHistoryItemRequestBuilder getHistoryItem() {
        return new GetHistoryItemRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Single History Item
     * 
     * <p>Get a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetHistoryItemResponse>} - The async response
     */
    public CompletableFuture<GetHistoryItemResponse> getHistoryItem(GetHistoryItemRequest request) {
        return getHistoryItem(request, Optional.empty());
    }

    /**
     * Get Single History Item
     * 
     * <p>Get a single history item by id
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetHistoryItemResponse>} - The async response
     */
    public CompletableFuture<GetHistoryItemResponse> getHistoryItem(GetHistoryItemRequest request, Optional<Options> options) {
        AsyncRequestOperation<GetHistoryItemRequest, GetHistoryItemResponse> operation
              = new GetHistoryItem.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
