/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.models.operations.EnablePapertrailRequest;
import dev.plexapi.sdk.models.operations.WriteMessageRequest;
import dev.plexapi.sdk.models.operations.async.EnablePapertrailRequestBuilder;
import dev.plexapi.sdk.models.operations.async.EnablePapertrailResponse;
import dev.plexapi.sdk.models.operations.async.WriteLogRequestBuilder;
import dev.plexapi.sdk.models.operations.async.WriteLogResponse;
import dev.plexapi.sdk.models.operations.async.WriteMessageRequestBuilder;
import dev.plexapi.sdk.models.operations.async.WriteMessageResponse;
import dev.plexapi.sdk.operations.EnablePapertrail;
import dev.plexapi.sdk.operations.WriteLog;
import dev.plexapi.sdk.operations.WriteMessage;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * Logging mechanism to allow clients to log to the server
 */
public class AsyncLog {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Log syncSDK;

    AsyncLog(Log syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Log sync() {
        return syncSDK;
    }


    /**
     * Logging a multi-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write multiple lines to the main Plex Media Server log in a single request. It
     * takes a set of query strings as would normally sent to the above PUT endpoint as a
     * linefeed-separated block of POST data. The parameters for each query string match as above.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public WriteLogRequestBuilder writeLog() {
        return new WriteLogRequestBuilder(sdkConfiguration);
    }

    /**
     * Logging a multi-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write multiple lines to the main Plex Media Server log in a single request. It
     * takes a set of query strings as would normally sent to the above PUT endpoint as a
     * linefeed-separated block of POST data. The parameters for each query string match as above.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<WriteLogResponse>} - The async response
     */
    public CompletableFuture<WriteLogResponse> writeLog(byte[] request) {
        return writeLog(request, Optional.empty());
    }

    /**
     * Logging a multi-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write multiple lines to the main Plex Media Server log in a single request. It
     * takes a set of query strings as would normally sent to the above PUT endpoint as a
     * linefeed-separated block of POST data. The parameters for each query string match as above.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<WriteLogResponse>} - The async response
     */
    public CompletableFuture<WriteLogResponse> writeLog(byte[] request, Optional<Options> options) {
        AsyncRequestOperation<byte[], WriteLogResponse> operation
              = new WriteLog.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Logging a single-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write a single-line log message, including a level and source to the main Plex
     * Media Server log.
     * 
     * <p>Note: This endpoint responds to all HTTP verbs **except POST** but PUT is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public WriteMessageRequestBuilder writeMessage() {
        return new WriteMessageRequestBuilder(sdkConfiguration);
    }

    /**
     * Logging a single-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write a single-line log message, including a level and source to the main Plex
     * Media Server log.
     * 
     * <p>Note: This endpoint responds to all HTTP verbs **except POST** but PUT is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<WriteMessageResponse>} - The async response
     */
    public CompletableFuture<WriteMessageResponse> writeMessage(WriteMessageRequest request) {
        return writeMessage(request, Optional.empty());
    }

    /**
     * Logging a single-line message to the Plex Media Server log
     * 
     * <p>This endpoint will write a single-line log message, including a level and source to the main Plex
     * Media Server log.
     * 
     * <p>Note: This endpoint responds to all HTTP verbs **except POST** but PUT is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<WriteMessageResponse>} - The async response
     */
    public CompletableFuture<WriteMessageResponse> writeMessage(WriteMessageRequest request, Optional<Options> options) {
        AsyncRequestOperation<WriteMessageRequest, WriteMessageResponse> operation
              = new WriteMessage.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Enabling Papertrail
     * 
     * <p>This endpoint will enable all Plex Media Server logs to be sent to the Papertrail networked logging
     * site for a period of time
     * 
     * <p>Note: This endpoint responds to all HTTP verbs but POST is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public EnablePapertrailRequestBuilder enablePapertrail() {
        return new EnablePapertrailRequestBuilder(sdkConfiguration);
    }

    /**
     * Enabling Papertrail
     * 
     * <p>This endpoint will enable all Plex Media Server logs to be sent to the Papertrail networked logging
     * site for a period of time
     * 
     * <p>Note: This endpoint responds to all HTTP verbs but POST is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<EnablePapertrailResponse>} - The async response
     */
    public CompletableFuture<EnablePapertrailResponse> enablePapertrail(EnablePapertrailRequest request) {
        return enablePapertrail(request, Optional.empty());
    }

    /**
     * Enabling Papertrail
     * 
     * <p>This endpoint will enable all Plex Media Server logs to be sent to the Papertrail networked logging
     * site for a period of time
     * 
     * <p>Note: This endpoint responds to all HTTP verbs but POST is preferred
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<EnablePapertrailResponse>} - The async response
     */
    public CompletableFuture<EnablePapertrailResponse> enablePapertrail(EnablePapertrailRequest request, Optional<Options> options) {
        AsyncRequestOperation<EnablePapertrailRequest, EnablePapertrailResponse> operation
              = new EnablePapertrail.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
