/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.models.operations.AddDeviceToDVRRequest;
import dev.plexapi.sdk.models.operations.AddLineupRequest;
import dev.plexapi.sdk.models.operations.CreateDVRRequest;
import dev.plexapi.sdk.models.operations.DeleteDVRRequest;
import dev.plexapi.sdk.models.operations.DeleteLineupRequest;
import dev.plexapi.sdk.models.operations.GetDVRChannelsRequest;
import dev.plexapi.sdk.models.operations.GetDVRGuideRequest;
import dev.plexapi.sdk.models.operations.GetDVRRequest;
import dev.plexapi.sdk.models.operations.ListDVRsRequest;
import dev.plexapi.sdk.models.operations.PatchDVRSettingsRequest;
import dev.plexapi.sdk.models.operations.ReloadGuideRequest;
import dev.plexapi.sdk.models.operations.RemoveDeviceFromDVRRequest;
import dev.plexapi.sdk.models.operations.SetDVRPreferencesRequest;
import dev.plexapi.sdk.models.operations.StopDVRReloadRequest;
import dev.plexapi.sdk.models.operations.TuneChannelRequest;
import dev.plexapi.sdk.models.operations.UpdateDVRSettingsRequest;
import dev.plexapi.sdk.models.operations.async.AddDeviceToDVRRequestBuilder;
import dev.plexapi.sdk.models.operations.async.AddDeviceToDVRResponse;
import dev.plexapi.sdk.models.operations.async.AddLineupRequestBuilder;
import dev.plexapi.sdk.models.operations.async.AddLineupResponse;
import dev.plexapi.sdk.models.operations.async.CreateDVRRequestBuilder;
import dev.plexapi.sdk.models.operations.async.CreateDVRResponse;
import dev.plexapi.sdk.models.operations.async.DeleteDVRRequestBuilder;
import dev.plexapi.sdk.models.operations.async.DeleteDVRResponse;
import dev.plexapi.sdk.models.operations.async.DeleteLineupRequestBuilder;
import dev.plexapi.sdk.models.operations.async.DeleteLineupResponse;
import dev.plexapi.sdk.models.operations.async.GetDVRChannelsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.GetDVRChannelsResponse;
import dev.plexapi.sdk.models.operations.async.GetDVRGuideRequestBuilder;
import dev.plexapi.sdk.models.operations.async.GetDVRGuideResponse;
import dev.plexapi.sdk.models.operations.async.GetDVRRequestBuilder;
import dev.plexapi.sdk.models.operations.async.GetDVRResponse;
import dev.plexapi.sdk.models.operations.async.ListDVRsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.ListDVRsResponse;
import dev.plexapi.sdk.models.operations.async.PatchDVRSettingsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.PatchDVRSettingsResponse;
import dev.plexapi.sdk.models.operations.async.ReloadGuideRequestBuilder;
import dev.plexapi.sdk.models.operations.async.ReloadGuideResponse;
import dev.plexapi.sdk.models.operations.async.RemoveDeviceFromDVRRequestBuilder;
import dev.plexapi.sdk.models.operations.async.RemoveDeviceFromDVRResponse;
import dev.plexapi.sdk.models.operations.async.SetDVRPreferencesRequestBuilder;
import dev.plexapi.sdk.models.operations.async.SetDVRPreferencesResponse;
import dev.plexapi.sdk.models.operations.async.StopDVRReloadRequestBuilder;
import dev.plexapi.sdk.models.operations.async.StopDVRReloadResponse;
import dev.plexapi.sdk.models.operations.async.TuneChannelRequestBuilder;
import dev.plexapi.sdk.models.operations.async.TuneChannelResponse;
import dev.plexapi.sdk.models.operations.async.UpdateDVRSettingsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.UpdateDVRSettingsResponse;
import dev.plexapi.sdk.operations.AddDeviceToDVR;
import dev.plexapi.sdk.operations.AddLineup;
import dev.plexapi.sdk.operations.CreateDVR;
import dev.plexapi.sdk.operations.DeleteDVR;
import dev.plexapi.sdk.operations.DeleteLineup;
import dev.plexapi.sdk.operations.GetDVR;
import dev.plexapi.sdk.operations.GetDVRChannels;
import dev.plexapi.sdk.operations.GetDVRGuide;
import dev.plexapi.sdk.operations.ListDVRs;
import dev.plexapi.sdk.operations.PatchDVRSettings;
import dev.plexapi.sdk.operations.ReloadGuide;
import dev.plexapi.sdk.operations.RemoveDeviceFromDVR;
import dev.plexapi.sdk.operations.SetDVRPreferences;
import dev.plexapi.sdk.operations.StopDVRReload;
import dev.plexapi.sdk.operations.TuneChannel;
import dev.plexapi.sdk.operations.UpdateDVRSettings;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * The DVR provides means to watch and record live TV. This section of endpoints describes how to setup
 * the DVR itself
 */
public class AsyncDVRs {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final DVRs syncSDK;

    AsyncDVRs(DVRs syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public DVRs sync() {
        return syncSDK;
    }


    /**
     * Get DVRs
     * 
     * <p>Get the list of all available DVRs
     * 
     * @return The async call builder
     */
    public ListDVRsRequestBuilder listDVRs() {
        return new ListDVRsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get DVRs
     * 
     * <p>Get the list of all available DVRs
     * 
     * @return {@code CompletableFuture<ListDVRsResponse>} - The async response
     */
    public CompletableFuture<ListDVRsResponse> listDVRsDirect() {
        return listDVRs(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Get DVRs
     * 
     * <p>Get the list of all available DVRs
     * 
     * @param uuid Filter by DVR UUID.
     * @param lineup Filter by lineup.
     * @param options additional options
     * @return {@code CompletableFuture<ListDVRsResponse>} - The async response
     */
    public CompletableFuture<ListDVRsResponse> listDVRs(
            Optional<String> uuid, Optional<String> lineup,
            Optional<Options> options) {
        ListDVRsRequest request =
            ListDVRsRequest
                .builder()
                .uuid(uuid)
                .lineup(lineup)
                .build();
        AsyncRequestOperation<ListDVRsRequest, ListDVRsResponse> operation
              = new ListDVRs.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Create a DVR
     * 
     * <p>Creation of a DVR, after creation of a device and a lineup is selected
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public CreateDVRRequestBuilder createDVR() {
        return new CreateDVRRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a DVR
     * 
     * <p>Creation of a DVR, after creation of a device and a lineup is selected
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<CreateDVRResponse>} - The async response
     */
    public CompletableFuture<CreateDVRResponse> createDVR(CreateDVRRequest request) {
        return createDVR(request, Optional.empty());
    }

    /**
     * Create a DVR
     * 
     * <p>Creation of a DVR, after creation of a device and a lineup is selected
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<CreateDVRResponse>} - The async response
     */
    public CompletableFuture<CreateDVRResponse> createDVR(CreateDVRRequest request, Optional<Options> options) {
        AsyncRequestOperation<CreateDVRRequest, CreateDVRResponse> operation
              = new CreateDVR.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a single DVR
     * 
     * <p>Delete a single DVR by its id (key)
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public DeleteDVRRequestBuilder deleteDVR() {
        return new DeleteDVRRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a single DVR
     * 
     * <p>Delete a single DVR by its id (key)
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<DeleteDVRResponse>} - The async response
     */
    public CompletableFuture<DeleteDVRResponse> deleteDVR(DeleteDVRRequest request) {
        return deleteDVR(request, Optional.empty());
    }

    /**
     * Delete a single DVR
     * 
     * <p>Delete a single DVR by its id (key)
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<DeleteDVRResponse>} - The async response
     */
    public CompletableFuture<DeleteDVRResponse> deleteDVR(DeleteDVRRequest request, Optional<Options> options) {
        AsyncRequestOperation<DeleteDVRRequest, DeleteDVRResponse> operation
              = new DeleteDVR.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a single DVR
     * 
     * <p>Get a single DVR by its id (key)
     * 
     * @return The async call builder
     */
    public GetDVRRequestBuilder getDVR() {
        return new GetDVRRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single DVR
     * 
     * <p>Get a single DVR by its id (key)
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetDVRResponse>} - The async response
     */
    public CompletableFuture<GetDVRResponse> getDVR(GetDVRRequest request) {
        return getDVR(request, Optional.empty());
    }

    /**
     * Get a single DVR
     * 
     * <p>Get a single DVR by its id (key)
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetDVRResponse>} - The async response
     */
    public CompletableFuture<GetDVRResponse> getDVR(GetDVRRequest request, Optional<Options> options) {
        AsyncRequestOperation<GetDVRRequest, GetDVRResponse> operation
              = new GetDVR.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public PatchDVRSettingsRequestBuilder patchDVRSettings() {
        return new PatchDVRSettingsRequestBuilder(sdkConfiguration);
    }

    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<PatchDVRSettingsResponse>} - The async response
     */
    public CompletableFuture<PatchDVRSettingsResponse> patchDVRSettings(PatchDVRSettingsRequest request) {
        return patchDVRSettings(request, Optional.empty());
    }

    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<PatchDVRSettingsResponse>} - The async response
     */
    public CompletableFuture<PatchDVRSettingsResponse> patchDVRSettings(PatchDVRSettingsRequest request, Optional<Options> options) {
        AsyncRequestOperation<PatchDVRSettingsRequest, PatchDVRSettingsResponse> operation
              = new PatchDVRSettings.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public UpdateDVRSettingsRequestBuilder updateDVRSettings() {
        return new UpdateDVRSettingsRequestBuilder(sdkConfiguration);
    }

    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<UpdateDVRSettingsResponse>} - The async response
     */
    public CompletableFuture<UpdateDVRSettingsResponse> updateDVRSettings(UpdateDVRSettingsRequest request) {
        return updateDVRSettings(request, Optional.empty());
    }

    /**
     * Update DVR Settings
     * 
     * <p>Update DVR settings.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<UpdateDVRSettingsResponse>} - The async response
     */
    public CompletableFuture<UpdateDVRSettingsResponse> updateDVRSettings(UpdateDVRSettingsRequest request, Optional<Options> options) {
        AsyncRequestOperation<UpdateDVRSettingsRequest, UpdateDVRSettingsResponse> operation
              = new UpdateDVRSettings.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get DVR Channels
     * 
     * <p>List channels directly associated with a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public GetDVRChannelsRequestBuilder getDVRChannels() {
        return new GetDVRChannelsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get DVR Channels
     * 
     * <p>List channels directly associated with a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetDVRChannelsResponse>} - The async response
     */
    public CompletableFuture<GetDVRChannelsResponse> getDVRChannels(GetDVRChannelsRequest request) {
        return getDVRChannels(request, Optional.empty());
    }

    /**
     * Get DVR Channels
     * 
     * <p>List channels directly associated with a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetDVRChannelsResponse>} - The async response
     */
    public CompletableFuture<GetDVRChannelsResponse> getDVRChannels(GetDVRChannelsRequest request, Optional<Options> options) {
        AsyncRequestOperation<GetDVRChannelsRequest, GetDVRChannelsResponse> operation
              = new GetDVRChannels.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get DVR Guide
     * 
     * <p>Fetch program guide/schedule for a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public GetDVRGuideRequestBuilder getDVRGuide() {
        return new GetDVRGuideRequestBuilder(sdkConfiguration);
    }

    /**
     * Get DVR Guide
     * 
     * <p>Fetch program guide/schedule for a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetDVRGuideResponse>} - The async response
     */
    public CompletableFuture<GetDVRGuideResponse> getDVRGuide(GetDVRGuideRequest request) {
        return getDVRGuide(request, Optional.empty());
    }

    /**
     * Get DVR Guide
     * 
     * <p>Fetch program guide/schedule for a DVR.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetDVRGuideResponse>} - The async response
     */
    public CompletableFuture<GetDVRGuideResponse> getDVRGuide(GetDVRGuideRequest request, Optional<Options> options) {
        AsyncRequestOperation<GetDVRGuideRequest, GetDVRGuideResponse> operation
              = new GetDVRGuide.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a DVR Lineup
     * 
     * <p>Deletes a DVR device's lineup.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public DeleteLineupRequestBuilder deleteLineup() {
        return new DeleteLineupRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a DVR Lineup
     * 
     * <p>Deletes a DVR device's lineup.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<DeleteLineupResponse>} - The async response
     */
    public CompletableFuture<DeleteLineupResponse> deleteLineup(DeleteLineupRequest request) {
        return deleteLineup(request, Optional.empty());
    }

    /**
     * Delete a DVR Lineup
     * 
     * <p>Deletes a DVR device's lineup.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<DeleteLineupResponse>} - The async response
     */
    public CompletableFuture<DeleteLineupResponse> deleteLineup(DeleteLineupRequest request, Optional<Options> options) {
        AsyncRequestOperation<DeleteLineupRequest, DeleteLineupResponse> operation
              = new DeleteLineup.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Add a DVR Lineup
     * 
     * <p>Add a lineup to a DVR device's set of lineups.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public AddLineupRequestBuilder addLineup() {
        return new AddLineupRequestBuilder(sdkConfiguration);
    }

    /**
     * Add a DVR Lineup
     * 
     * <p>Add a lineup to a DVR device's set of lineups.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AddLineupResponse>} - The async response
     */
    public CompletableFuture<AddLineupResponse> addLineup(AddLineupRequest request) {
        return addLineup(request, Optional.empty());
    }

    /**
     * Add a DVR Lineup
     * 
     * <p>Add a lineup to a DVR device's set of lineups.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AddLineupResponse>} - The async response
     */
    public CompletableFuture<AddLineupResponse> addLineup(AddLineupRequest request, Optional<Options> options) {
        AsyncRequestOperation<AddLineupRequest, AddLineupResponse> operation
              = new AddLineup.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Set DVR preferences
     * 
     * <p>Set DVR preferences by name and value
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public SetDVRPreferencesRequestBuilder setDVRPreferences() {
        return new SetDVRPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Set DVR preferences
     * 
     * <p>Set DVR preferences by name and value
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SetDVRPreferencesResponse>} - The async response
     */
    public CompletableFuture<SetDVRPreferencesResponse> setDVRPreferences(SetDVRPreferencesRequest request) {
        return setDVRPreferences(request, Optional.empty());
    }

    /**
     * Set DVR preferences
     * 
     * <p>Set DVR preferences by name and value
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SetDVRPreferencesResponse>} - The async response
     */
    public CompletableFuture<SetDVRPreferencesResponse> setDVRPreferences(SetDVRPreferencesRequest request, Optional<Options> options) {
        AsyncRequestOperation<SetDVRPreferencesRequest, SetDVRPreferencesResponse> operation
              = new SetDVRPreferences.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Tell a DVR to stop reloading program guide
     * 
     * <p>Tell a DVR to stop reloading program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public StopDVRReloadRequestBuilder stopDVRReload() {
        return new StopDVRReloadRequestBuilder(sdkConfiguration);
    }

    /**
     * Tell a DVR to stop reloading program guide
     * 
     * <p>Tell a DVR to stop reloading program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<StopDVRReloadResponse>} - The async response
     */
    public CompletableFuture<StopDVRReloadResponse> stopDVRReload(StopDVRReloadRequest request) {
        return stopDVRReload(request, Optional.empty());
    }

    /**
     * Tell a DVR to stop reloading program guide
     * 
     * <p>Tell a DVR to stop reloading program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<StopDVRReloadResponse>} - The async response
     */
    public CompletableFuture<StopDVRReloadResponse> stopDVRReload(StopDVRReloadRequest request, Optional<Options> options) {
        AsyncRequestOperation<StopDVRReloadRequest, StopDVRReloadResponse> operation
              = new StopDVRReload.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Tell a DVR to reload program guide
     * 
     * <p>Tell a DVR to reload program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public ReloadGuideRequestBuilder reloadGuide() {
        return new ReloadGuideRequestBuilder(sdkConfiguration);
    }

    /**
     * Tell a DVR to reload program guide
     * 
     * <p>Tell a DVR to reload program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ReloadGuideResponse>} - The async response
     */
    public CompletableFuture<ReloadGuideResponse> reloadGuide(ReloadGuideRequest request) {
        return reloadGuide(request, Optional.empty());
    }

    /**
     * Tell a DVR to reload program guide
     * 
     * <p>Tell a DVR to reload program guide
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ReloadGuideResponse>} - The async response
     */
    public CompletableFuture<ReloadGuideResponse> reloadGuide(ReloadGuideRequest request, Optional<Options> options) {
        AsyncRequestOperation<ReloadGuideRequest, ReloadGuideResponse> operation
              = new ReloadGuide.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Tune a channel on a DVR
     * 
     * <p>Tune a channel on a DVR to the provided channel
     * 
     * @return The async call builder
     */
    public TuneChannelRequestBuilder tuneChannel() {
        return new TuneChannelRequestBuilder(sdkConfiguration);
    }

    /**
     * Tune a channel on a DVR
     * 
     * <p>Tune a channel on a DVR to the provided channel
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<TuneChannelResponse>} - The async response
     */
    public CompletableFuture<TuneChannelResponse> tuneChannel(TuneChannelRequest request) {
        return tuneChannel(request, Optional.empty());
    }

    /**
     * Tune a channel on a DVR
     * 
     * <p>Tune a channel on a DVR to the provided channel
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<TuneChannelResponse>} - The async response
     */
    public CompletableFuture<TuneChannelResponse> tuneChannel(TuneChannelRequest request, Optional<Options> options) {
        AsyncRequestOperation<TuneChannelRequest, TuneChannelResponse> operation
              = new TuneChannel.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Remove a device from an existing DVR
     * 
     * <p>Remove a device from an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public RemoveDeviceFromDVRRequestBuilder removeDeviceFromDVR() {
        return new RemoveDeviceFromDVRRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a device from an existing DVR
     * 
     * <p>Remove a device from an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<RemoveDeviceFromDVRResponse>} - The async response
     */
    public CompletableFuture<RemoveDeviceFromDVRResponse> removeDeviceFromDVR(RemoveDeviceFromDVRRequest request) {
        return removeDeviceFromDVR(request, Optional.empty());
    }

    /**
     * Remove a device from an existing DVR
     * 
     * <p>Remove a device from an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<RemoveDeviceFromDVRResponse>} - The async response
     */
    public CompletableFuture<RemoveDeviceFromDVRResponse> removeDeviceFromDVR(RemoveDeviceFromDVRRequest request, Optional<Options> options) {
        AsyncRequestOperation<RemoveDeviceFromDVRRequest, RemoveDeviceFromDVRResponse> operation
              = new RemoveDeviceFromDVR.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Add a device to an existing DVR
     * 
     * <p>Add a device to an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The async call builder
     */
    public AddDeviceToDVRRequestBuilder addDeviceToDVR() {
        return new AddDeviceToDVRRequestBuilder(sdkConfiguration);
    }

    /**
     * Add a device to an existing DVR
     * 
     * <p>Add a device to an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AddDeviceToDVRResponse>} - The async response
     */
    public CompletableFuture<AddDeviceToDVRResponse> addDeviceToDVR(AddDeviceToDVRRequest request) {
        return addDeviceToDVR(request, Optional.empty());
    }

    /**
     * Add a device to an existing DVR
     * 
     * <p>Add a device to an existing DVR
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AddDeviceToDVRResponse>} - The async response
     */
    public CompletableFuture<AddDeviceToDVRResponse> addDeviceToDVR(AddDeviceToDVRRequest request, Optional<Options> options) {
        AsyncRequestOperation<AddDeviceToDVRRequest, AddDeviceToDVRResponse> operation
              = new AddDeviceToDVR.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
