/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.models.operations.CreateCollectionRequest;
import dev.plexapi.sdk.models.operations.CreateCollectionRequestBuilder;
import dev.plexapi.sdk.models.operations.CreateCollectionResponse;
import dev.plexapi.sdk.operations.CreateCollection;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;

/**
 * API Operations against the Collections
 */
public class Collections {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncCollections asyncSDK;

    Collections(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncCollections(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncCollections async() {
        return asyncSDK;
    }

    /**
     * Create collection
     * 
     * <p>Create a collection in the library
     * 
     * @return The call builder
     */
    public CreateCollectionRequestBuilder createCollection() {
        return new CreateCollectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Create collection
     * 
     * <p>Create a collection in the library
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateCollectionResponse createCollection(CreateCollectionRequest request) {
        return createCollection(request, Optional.empty());
    }

    /**
     * Create collection
     * 
     * <p>Create a collection in the library
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateCollectionResponse createCollection(CreateCollectionRequest request, Optional<Options> options) {
        RequestOperation<CreateCollectionRequest, CreateCollectionResponse> operation
              = new CreateCollection.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
