/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.RequestlessOperation;
import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.models.operations.AddDownloadQueueItemsRequest;
import dev.plexapi.sdk.models.operations.AddDownloadQueueItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.AddDownloadQueueItemsResponse;
import dev.plexapi.sdk.models.operations.CreateDownloadQueueRequestBuilder;
import dev.plexapi.sdk.models.operations.CreateDownloadQueueResponse;
import dev.plexapi.sdk.models.operations.GetDownloadQueueItemsRequest;
import dev.plexapi.sdk.models.operations.GetDownloadQueueItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.GetDownloadQueueItemsResponse;
import dev.plexapi.sdk.models.operations.GetDownloadQueueMediaRequest;
import dev.plexapi.sdk.models.operations.GetDownloadQueueMediaRequestBuilder;
import dev.plexapi.sdk.models.operations.GetDownloadQueueMediaResponse;
import dev.plexapi.sdk.models.operations.GetDownloadQueueRequest;
import dev.plexapi.sdk.models.operations.GetDownloadQueueRequestBuilder;
import dev.plexapi.sdk.models.operations.GetDownloadQueueResponse;
import dev.plexapi.sdk.models.operations.GetItemDecisionRequest;
import dev.plexapi.sdk.models.operations.GetItemDecisionRequestBuilder;
import dev.plexapi.sdk.models.operations.GetItemDecisionResponse;
import dev.plexapi.sdk.models.operations.ListDownloadQueueItemsRequest;
import dev.plexapi.sdk.models.operations.ListDownloadQueueItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.ListDownloadQueueItemsResponse;
import dev.plexapi.sdk.models.operations.RemoveDownloadQueueItemsRequest;
import dev.plexapi.sdk.models.operations.RemoveDownloadQueueItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.RemoveDownloadQueueItemsResponse;
import dev.plexapi.sdk.models.operations.RestartProcessingDownloadQueueItemsRequest;
import dev.plexapi.sdk.models.operations.RestartProcessingDownloadQueueItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.RestartProcessingDownloadQueueItemsResponse;
import dev.plexapi.sdk.operations.AddDownloadQueueItems;
import dev.plexapi.sdk.operations.CreateDownloadQueue;
import dev.plexapi.sdk.operations.GetDownloadQueue;
import dev.plexapi.sdk.operations.GetDownloadQueueItems;
import dev.plexapi.sdk.operations.GetDownloadQueueMedia;
import dev.plexapi.sdk.operations.GetItemDecision;
import dev.plexapi.sdk.operations.ListDownloadQueueItems;
import dev.plexapi.sdk.operations.RemoveDownloadQueueItems;
import dev.plexapi.sdk.operations.RestartProcessingDownloadQueueItems;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;

/**
 * API Operations against the Download Queue.
 * Note: The Download Queue is distinct from the Play Queue. The Download Queue manages
 * offline/downloaded content, while the Play Queue manages active playback sessions.
 */
public class DownloadQueue {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncDownloadQueue asyncSDK;

    DownloadQueue(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncDownloadQueue(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncDownloadQueue async() {
        return asyncSDK;
    }

    /**
     * Create download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Creates a download queue for this client if one doesn't exist, or returns the existing queue for
     * this client and user.
     * 
     * @return The call builder
     */
    public CreateDownloadQueueRequestBuilder createDownloadQueue() {
        return new CreateDownloadQueueRequestBuilder(sdkConfiguration);
    }

    /**
     * Create download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Creates a download queue for this client if one doesn't exist, or returns the existing queue for
     * this client and user.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateDownloadQueueResponse createDownloadQueueDirect() {
        return createDownloadQueue(Optional.empty());
    }

    /**
     * Create download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Creates a download queue for this client if one doesn't exist, or returns the existing queue for
     * this client and user.
     * 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateDownloadQueueResponse createDownloadQueue(Optional<Options> options) {
        RequestlessOperation<CreateDownloadQueueResponse> operation
            = new CreateDownloadQueue.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Get a download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get a download queue by its id
     * 
     * @return The call builder
     */
    public GetDownloadQueueRequestBuilder getDownloadQueue() {
        return new GetDownloadQueueRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get a download queue by its id
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueResponse getDownloadQueue(GetDownloadQueueRequest request) {
        return getDownloadQueue(request, Optional.empty());
    }

    /**
     * Get a download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get a download queue by its id
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueResponse getDownloadQueue(GetDownloadQueueRequest request, Optional<Options> options) {
        RequestOperation<GetDownloadQueueRequest, GetDownloadQueueResponse> operation
              = new GetDownloadQueue.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add to download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Add items to the download queue
     * 
     * @return The call builder
     */
    public AddDownloadQueueItemsRequestBuilder addDownloadQueueItems() {
        return new AddDownloadQueueItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Add to download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Add items to the download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AddDownloadQueueItemsResponse addDownloadQueueItems(AddDownloadQueueItemsRequest request) {
        return addDownloadQueueItems(request, Optional.empty());
    }

    /**
     * Add to download queue
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Add items to the download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AddDownloadQueueItemsResponse addDownloadQueueItems(AddDownloadQueueItemsRequest request, Optional<Options> options) {
        RequestOperation<AddDownloadQueueItemsRequest, AddDownloadQueueItemsResponse> operation
              = new AddDownloadQueueItems.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @return The call builder
     */
    public ListDownloadQueueItemsRequestBuilder listDownloadQueueItems() {
        return new ListDownloadQueueItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListDownloadQueueItemsResponse listDownloadQueueItems(ListDownloadQueueItemsRequest request) {
        return listDownloadQueueItems(request, Optional.empty());
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListDownloadQueueItemsResponse listDownloadQueueItems(ListDownloadQueueItemsRequest request, Optional<Options> options) {
        RequestOperation<ListDownloadQueueItemsRequest, ListDownloadQueueItemsResponse> operation
              = new ListDownloadQueueItems.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Grab download queue item decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the decision for a download queue item
     * 
     * @return The call builder
     */
    public GetItemDecisionRequestBuilder getItemDecision() {
        return new GetItemDecisionRequestBuilder(sdkConfiguration);
    }

    /**
     * Grab download queue item decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the decision for a download queue item
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetItemDecisionResponse getItemDecision(GetItemDecisionRequest request) {
        return getItemDecision(request, Optional.empty());
    }

    /**
     * Grab download queue item decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the decision for a download queue item
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetItemDecisionResponse getItemDecision(GetItemDecisionRequest request, Optional<Options> options) {
        RequestOperation<GetItemDecisionRequest, GetItemDecisionResponse> operation
              = new GetItemDecision.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Grab download queue media
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the media for a download queue item
     * 
     * @return The call builder
     */
    public GetDownloadQueueMediaRequestBuilder getDownloadQueueMedia() {
        return new GetDownloadQueueMediaRequestBuilder(sdkConfiguration);
    }

    /**
     * Grab download queue media
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the media for a download queue item
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueMediaResponse getDownloadQueueMedia(GetDownloadQueueMediaRequest request) {
        return getDownloadQueueMedia(request, Optional.empty());
    }

    /**
     * Grab download queue media
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Grab the media for a download queue item
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueMediaResponse getDownloadQueueMedia(GetDownloadQueueMediaRequest request, Optional<Options> options) {
        RequestOperation<GetDownloadQueueMediaRequest, GetDownloadQueueMediaResponse> operation
              = new GetDownloadQueueMedia.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete download queue items
     * 
     * <p>delete items from a download queue
     * 
     * @return The call builder
     */
    public RemoveDownloadQueueItemsRequestBuilder removeDownloadQueueItems() {
        return new RemoveDownloadQueueItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete download queue items
     * 
     * <p>delete items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemoveDownloadQueueItemsResponse removeDownloadQueueItems(RemoveDownloadQueueItemsRequest request) {
        return removeDownloadQueueItems(request, Optional.empty());
    }

    /**
     * Delete download queue items
     * 
     * <p>delete items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemoveDownloadQueueItemsResponse removeDownloadQueueItems(RemoveDownloadQueueItemsRequest request, Optional<Options> options) {
        RequestOperation<RemoveDownloadQueueItemsRequest, RemoveDownloadQueueItemsResponse> operation
              = new RemoveDownloadQueueItems.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @return The call builder
     */
    public GetDownloadQueueItemsRequestBuilder getDownloadQueueItems() {
        return new GetDownloadQueueItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueItemsResponse getDownloadQueueItems(GetDownloadQueueItemsRequest request) {
        return getDownloadQueueItems(request, Optional.empty());
    }

    /**
     * Get download queue items
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Get items from a download queue
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDownloadQueueItemsResponse getDownloadQueueItems(GetDownloadQueueItemsRequest request, Optional<Options> options) {
        RequestOperation<GetDownloadQueueItemsRequest, GetDownloadQueueItemsResponse> operation
              = new GetDownloadQueueItems.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Restart processing of items from the decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Reprocess download queue items with previous decision parameters
     * 
     * @return The call builder
     */
    public RestartProcessingDownloadQueueItemsRequestBuilder restartProcessingDownloadQueueItems() {
        return new RestartProcessingDownloadQueueItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Restart processing of items from the decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Reprocess download queue items with previous decision parameters
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RestartProcessingDownloadQueueItemsResponse restartProcessingDownloadQueueItems(RestartProcessingDownloadQueueItemsRequest request) {
        return restartProcessingDownloadQueueItems(request, Optional.empty());
    }

    /**
     * Restart processing of items from the decision
     * 
     * <p>Available: 0.2.0
     * 
     * <p>Reprocess download queue items with previous decision parameters
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RestartProcessingDownloadQueueItemsResponse restartProcessingDownloadQueueItems(RestartProcessingDownloadQueueItemsRequest request, Optional<Options> options) {
        RequestOperation<RestartProcessingDownloadQueueItemsRequest, RestartProcessingDownloadQueueItemsResponse> operation
              = new RestartProcessingDownloadQueueItems.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
