/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.models.operations.GetClientResourcesRequest;
import dev.plexapi.sdk.models.operations.GetClientResourcesRequestBuilder;
import dev.plexapi.sdk.models.operations.GetClientResourcesResponse;
import dev.plexapi.sdk.models.operations.GetProgressRequest;
import dev.plexapi.sdk.models.operations.GetProgressRequestBuilder;
import dev.plexapi.sdk.models.operations.GetProgressResponse;
import dev.plexapi.sdk.models.operations.PlayerAudioStreamRequest;
import dev.plexapi.sdk.models.operations.PlayerAudioStreamRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerAudioStreamResponse;
import dev.plexapi.sdk.models.operations.PlayerMuteRequest;
import dev.plexapi.sdk.models.operations.PlayerMuteRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerMuteResponse;
import dev.plexapi.sdk.models.operations.PlayerPauseRequest;
import dev.plexapi.sdk.models.operations.PlayerPauseRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerPauseResponse;
import dev.plexapi.sdk.models.operations.PlayerPlayMediaRequest;
import dev.plexapi.sdk.models.operations.PlayerPlayMediaRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerPlayMediaResponse;
import dev.plexapi.sdk.models.operations.PlayerPlayRequest;
import dev.plexapi.sdk.models.operations.PlayerPlayRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerPlayResponse;
import dev.plexapi.sdk.models.operations.PlayerPollTimelineRequest;
import dev.plexapi.sdk.models.operations.PlayerPollTimelineRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerPollTimelineResponse;
import dev.plexapi.sdk.models.operations.PlayerRefreshplayqueueRequest;
import dev.plexapi.sdk.models.operations.PlayerRefreshplayqueueRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerRefreshplayqueueResponse;
import dev.plexapi.sdk.models.operations.PlayerSeekRequest;
import dev.plexapi.sdk.models.operations.PlayerSeekRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSeekResponse;
import dev.plexapi.sdk.models.operations.PlayerSetParametersRequest;
import dev.plexapi.sdk.models.operations.PlayerSetParametersRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetParametersResponse;
import dev.plexapi.sdk.models.operations.PlayerSetRatingRequest;
import dev.plexapi.sdk.models.operations.PlayerSetRatingRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetRatingResponse;
import dev.plexapi.sdk.models.operations.PlayerSetStateRequest;
import dev.plexapi.sdk.models.operations.PlayerSetStateRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetStateResponse;
import dev.plexapi.sdk.models.operations.PlayerSetStreamsRequest;
import dev.plexapi.sdk.models.operations.PlayerSetStreamsRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetStreamsResponse;
import dev.plexapi.sdk.models.operations.PlayerSetTextStreamRequest;
import dev.plexapi.sdk.models.operations.PlayerSetTextStreamRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetTextStreamResponse;
import dev.plexapi.sdk.models.operations.PlayerSetViewOffsetRequest;
import dev.plexapi.sdk.models.operations.PlayerSetViewOffsetRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSetViewOffsetResponse;
import dev.plexapi.sdk.models.operations.PlayerSkipByRequest;
import dev.plexapi.sdk.models.operations.PlayerSkipByRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSkipByResponse;
import dev.plexapi.sdk.models.operations.PlayerSkipToRequest;
import dev.plexapi.sdk.models.operations.PlayerSkipToRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSkipToResponse;
import dev.plexapi.sdk.models.operations.PlayerStepbackRequest;
import dev.plexapi.sdk.models.operations.PlayerStepbackRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerStepbackResponse;
import dev.plexapi.sdk.models.operations.PlayerStepforwardRequest;
import dev.plexapi.sdk.models.operations.PlayerStepforwardRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerStepforwardResponse;
import dev.plexapi.sdk.models.operations.PlayerStopRequest;
import dev.plexapi.sdk.models.operations.PlayerStopRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerStopResponse;
import dev.plexapi.sdk.models.operations.PlayerSubtitleStreamRequest;
import dev.plexapi.sdk.models.operations.PlayerSubtitleStreamRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerSubtitleStreamResponse;
import dev.plexapi.sdk.models.operations.PlayerUnmuteRequest;
import dev.plexapi.sdk.models.operations.PlayerUnmuteRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerUnmuteResponse;
import dev.plexapi.sdk.models.operations.PlayerVideoStreamRequest;
import dev.plexapi.sdk.models.operations.PlayerVideoStreamRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerVideoStreamResponse;
import dev.plexapi.sdk.models.operations.PlayerVolumeRequest;
import dev.plexapi.sdk.models.operations.PlayerVolumeRequestBuilder;
import dev.plexapi.sdk.models.operations.PlayerVolumeResponse;
import dev.plexapi.sdk.models.operations.RemoveFromContinueWatchingRequest;
import dev.plexapi.sdk.models.operations.RemoveFromContinueWatchingRequestBuilder;
import dev.plexapi.sdk.models.operations.RemoveFromContinueWatchingResponse;
import dev.plexapi.sdk.operations.GetClientResources;
import dev.plexapi.sdk.operations.GetProgress;
import dev.plexapi.sdk.operations.PlayerAudioStream;
import dev.plexapi.sdk.operations.PlayerMute;
import dev.plexapi.sdk.operations.PlayerPause;
import dev.plexapi.sdk.operations.PlayerPlay;
import dev.plexapi.sdk.operations.PlayerPlayMedia;
import dev.plexapi.sdk.operations.PlayerPollTimeline;
import dev.plexapi.sdk.operations.PlayerRefreshplayqueue;
import dev.plexapi.sdk.operations.PlayerSeek;
import dev.plexapi.sdk.operations.PlayerSetParameters;
import dev.plexapi.sdk.operations.PlayerSetRating;
import dev.plexapi.sdk.operations.PlayerSetState;
import dev.plexapi.sdk.operations.PlayerSetStreams;
import dev.plexapi.sdk.operations.PlayerSetTextStream;
import dev.plexapi.sdk.operations.PlayerSetViewOffset;
import dev.plexapi.sdk.operations.PlayerSkipBy;
import dev.plexapi.sdk.operations.PlayerSkipTo;
import dev.plexapi.sdk.operations.PlayerStepback;
import dev.plexapi.sdk.operations.PlayerStepforward;
import dev.plexapi.sdk.operations.PlayerStop;
import dev.plexapi.sdk.operations.PlayerSubtitleStream;
import dev.plexapi.sdk.operations.PlayerUnmute;
import dev.plexapi.sdk.operations.PlayerVideoStream;
import dev.plexapi.sdk.operations.PlayerVolume;
import dev.plexapi.sdk.operations.RemoveFromContinueWatching;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;

/**
 * Plex Playback operations
 */
public class Playback {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncPlayback asyncSDK;

    Playback(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncPlayback(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncPlayback async() {
        return asyncSDK;
    }

    /**
     * Get Progress
     * 
     * <p>Get or update watch progress for a media item.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The call builder
     */
    public GetProgressRequestBuilder getProgress() {
        return new GetProgressRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Progress
     * 
     * <p>Get or update watch progress for a media item.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetProgressResponse getProgress(GetProgressRequest request) {
        return getProgress(request, Optional.empty());
    }

    /**
     * Get Progress
     * 
     * <p>Get or update watch progress for a media item.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetProgressResponse getProgress(GetProgressRequest request, Optional<Options> options) {
        RequestOperation<GetProgressRequest, GetProgressResponse> operation
              = new GetProgress.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove From Continue Watching
     * 
     * <p>Remove an item from the Continue Watching list.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @return The call builder
     */
    public RemoveFromContinueWatchingRequestBuilder removeFromContinueWatching() {
        return new RemoveFromContinueWatchingRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove From Continue Watching
     * 
     * <p>Remove an item from the Continue Watching list.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemoveFromContinueWatchingResponse removeFromContinueWatching(RemoveFromContinueWatchingRequest request) {
        return removeFromContinueWatching(request, Optional.empty());
    }

    /**
     * Remove From Continue Watching
     * 
     * <p>Remove an item from the Continue Watching list.
     * 
     * <p>If set, this operation will use Security#token from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemoveFromContinueWatchingResponse removeFromContinueWatching(RemoveFromContinueWatchingRequest request, Optional<Options> options) {
        RequestOperation<RemoveFromContinueWatchingRequest, RemoveFromContinueWatchingResponse> operation
              = new RemoveFromContinueWatching.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Audio Stream
     * 
     * <p>Change the active audio stream.
     * 
     * @return The call builder
     */
    public PlayerAudioStreamRequestBuilder playerAudioStream() {
        return new PlayerAudioStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Audio Stream
     * 
     * <p>Change the active audio stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerAudioStreamResponse playerAudioStream(PlayerAudioStreamRequest request) {
        return playerAudioStream(request, Optional.empty());
    }

    /**
     * Player Audio Stream
     * 
     * <p>Change the active audio stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerAudioStreamResponse playerAudioStream(PlayerAudioStreamRequest request, Optional<Options> options) {
        RequestOperation<PlayerAudioStreamRequest, PlayerAudioStreamResponse> operation
              = new PlayerAudioStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Mute
     * 
     * <p>Mute the client audio
     * 
     * @return The call builder
     */
    public PlayerMuteRequestBuilder playerMute() {
        return new PlayerMuteRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Mute
     * 
     * <p>Mute the client audio
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerMuteResponse playerMute(PlayerMuteRequest request) {
        return playerMute(request, Optional.empty());
    }

    /**
     * Player Mute
     * 
     * <p>Mute the client audio
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerMuteResponse playerMute(PlayerMuteRequest request, Optional<Options> options) {
        RequestOperation<PlayerMuteRequest, PlayerMuteResponse> operation
              = new PlayerMute.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Pause
     * 
     * <p>Pause playback on the client
     * 
     * @return The call builder
     */
    public PlayerPauseRequestBuilder playerPause() {
        return new PlayerPauseRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Pause
     * 
     * <p>Pause playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPauseResponse playerPause(PlayerPauseRequest request) {
        return playerPause(request, Optional.empty());
    }

    /**
     * Player Pause
     * 
     * <p>Pause playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPauseResponse playerPause(PlayerPauseRequest request, Optional<Options> options) {
        RequestOperation<PlayerPauseRequest, PlayerPauseResponse> operation
              = new PlayerPause.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Play
     * 
     * <p>Start playback on the client
     * 
     * @return The call builder
     */
    public PlayerPlayRequestBuilder playerPlay() {
        return new PlayerPlayRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Play
     * 
     * <p>Start playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPlayResponse playerPlay(PlayerPlayRequest request) {
        return playerPlay(request, Optional.empty());
    }

    /**
     * Player Play
     * 
     * <p>Start playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPlayResponse playerPlay(PlayerPlayRequest request, Optional<Options> options) {
        RequestOperation<PlayerPlayRequest, PlayerPlayResponse> operation
              = new PlayerPlay.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Play Media
     * 
     * <p>Play a specific media item on the client.
     * 
     * @return The call builder
     */
    public PlayerPlayMediaRequestBuilder playerPlayMedia() {
        return new PlayerPlayMediaRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Play Media
     * 
     * <p>Play a specific media item on the client.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPlayMediaResponse playerPlayMedia(PlayerPlayMediaRequest request) {
        return playerPlayMedia(request, Optional.empty());
    }

    /**
     * Player Play Media
     * 
     * <p>Play a specific media item on the client.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPlayMediaResponse playerPlayMedia(PlayerPlayMediaRequest request, Optional<Options> options) {
        RequestOperation<PlayerPlayMediaRequest, PlayerPlayMediaResponse> operation
              = new PlayerPlayMedia.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Refresh Play Queue
     * 
     * <p>Refresh the play queue on the client
     * 
     * @return The call builder
     */
    public PlayerRefreshplayqueueRequestBuilder playerRefreshplayqueue() {
        return new PlayerRefreshplayqueueRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Refresh Play Queue
     * 
     * <p>Refresh the play queue on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerRefreshplayqueueResponse playerRefreshplayqueue(PlayerRefreshplayqueueRequest request) {
        return playerRefreshplayqueue(request, Optional.empty());
    }

    /**
     * Player Refresh Play Queue
     * 
     * <p>Refresh the play queue on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerRefreshplayqueueResponse playerRefreshplayqueue(PlayerRefreshplayqueueRequest request, Optional<Options> options) {
        RequestOperation<PlayerRefreshplayqueueRequest, PlayerRefreshplayqueueResponse> operation
              = new PlayerRefreshplayqueue.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Seek
     * 
     * <p>Seek to a specific time in the current playback.
     * 
     * @return The call builder
     */
    public PlayerSeekRequestBuilder playerSeek() {
        return new PlayerSeekRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Seek
     * 
     * <p>Seek to a specific time in the current playback.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSeekResponse playerSeek(PlayerSeekRequest request) {
        return playerSeek(request, Optional.empty());
    }

    /**
     * Player Seek
     * 
     * <p>Seek to a specific time in the current playback.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSeekResponse playerSeek(PlayerSeekRequest request, Optional<Options> options) {
        RequestOperation<PlayerSeekRequest, PlayerSeekResponse> operation
              = new PlayerSeek.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set Parameters
     * 
     * <p>Set shuffle, repeat, and volume parameters.
     * 
     * @return The call builder
     */
    public PlayerSetParametersRequestBuilder playerSetParameters() {
        return new PlayerSetParametersRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set Parameters
     * 
     * <p>Set shuffle, repeat, and volume parameters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetParametersResponse playerSetParameters(PlayerSetParametersRequest request) {
        return playerSetParameters(request, Optional.empty());
    }

    /**
     * Player Set Parameters
     * 
     * <p>Set shuffle, repeat, and volume parameters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetParametersResponse playerSetParameters(PlayerSetParametersRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetParametersRequest, PlayerSetParametersResponse> operation
              = new PlayerSetParameters.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set Rating
     * 
     * <p>Rate the currently playing item.
     * 
     * @return The call builder
     */
    public PlayerSetRatingRequestBuilder playerSetRating() {
        return new PlayerSetRatingRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set Rating
     * 
     * <p>Rate the currently playing item.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetRatingResponse playerSetRating(PlayerSetRatingRequest request) {
        return playerSetRating(request, Optional.empty());
    }

    /**
     * Player Set Rating
     * 
     * <p>Rate the currently playing item.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetRatingResponse playerSetRating(PlayerSetRatingRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetRatingRequest, PlayerSetRatingResponse> operation
              = new PlayerSetRating.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set State
     * 
     * <p>Set the playback state directly.
     * 
     * @return The call builder
     */
    public PlayerSetStateRequestBuilder playerSetState() {
        return new PlayerSetStateRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set State
     * 
     * <p>Set the playback state directly.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetStateResponse playerSetState(PlayerSetStateRequest request) {
        return playerSetState(request, Optional.empty());
    }

    /**
     * Player Set State
     * 
     * <p>Set the playback state directly.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetStateResponse playerSetState(PlayerSetStateRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetStateRequest, PlayerSetStateResponse> operation
              = new PlayerSetState.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set Streams
     * 
     * <p>Set active audio, subtitle, and video streams.
     * 
     * @return The call builder
     */
    public PlayerSetStreamsRequestBuilder playerSetStreams() {
        return new PlayerSetStreamsRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set Streams
     * 
     * <p>Set active audio, subtitle, and video streams.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetStreamsResponse playerSetStreams(PlayerSetStreamsRequest request) {
        return playerSetStreams(request, Optional.empty());
    }

    /**
     * Player Set Streams
     * 
     * <p>Set active audio, subtitle, and video streams.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetStreamsResponse playerSetStreams(PlayerSetStreamsRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetStreamsRequest, PlayerSetStreamsResponse> operation
              = new PlayerSetStreams.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set Text Stream
     * 
     * <p>Set the active text stream.
     * 
     * @return The call builder
     */
    public PlayerSetTextStreamRequestBuilder playerSetTextStream() {
        return new PlayerSetTextStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set Text Stream
     * 
     * <p>Set the active text stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetTextStreamResponse playerSetTextStream(PlayerSetTextStreamRequest request) {
        return playerSetTextStream(request, Optional.empty());
    }

    /**
     * Player Set Text Stream
     * 
     * <p>Set the active text stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetTextStreamResponse playerSetTextStream(PlayerSetTextStreamRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetTextStreamRequest, PlayerSetTextStreamResponse> operation
              = new PlayerSetTextStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Set View Offset
     * 
     * <p>Set the resume offset for the current item.
     * 
     * @return The call builder
     */
    public PlayerSetViewOffsetRequestBuilder playerSetViewOffset() {
        return new PlayerSetViewOffsetRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Set View Offset
     * 
     * <p>Set the resume offset for the current item.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetViewOffsetResponse playerSetViewOffset(PlayerSetViewOffsetRequest request) {
        return playerSetViewOffset(request, Optional.empty());
    }

    /**
     * Player Set View Offset
     * 
     * <p>Set the resume offset for the current item.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSetViewOffsetResponse playerSetViewOffset(PlayerSetViewOffsetRequest request, Optional<Options> options) {
        RequestOperation<PlayerSetViewOffsetRequest, PlayerSetViewOffsetResponse> operation
              = new PlayerSetViewOffset.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Skip By
     * 
     * <p>Skip forward or backward by a number of items.
     * 
     * @return The call builder
     */
    public PlayerSkipByRequestBuilder playerSkipBy() {
        return new PlayerSkipByRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Skip By
     * 
     * <p>Skip forward or backward by a number of items.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSkipByResponse playerSkipBy(PlayerSkipByRequest request) {
        return playerSkipBy(request, Optional.empty());
    }

    /**
     * Player Skip By
     * 
     * <p>Skip forward or backward by a number of items.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSkipByResponse playerSkipBy(PlayerSkipByRequest request, Optional<Options> options) {
        RequestOperation<PlayerSkipByRequest, PlayerSkipByResponse> operation
              = new PlayerSkipBy.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Skip To
     * 
     * <p>Skip to a specific item in the play queue.
     * 
     * @return The call builder
     */
    public PlayerSkipToRequestBuilder playerSkipTo() {
        return new PlayerSkipToRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Skip To
     * 
     * <p>Skip to a specific item in the play queue.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSkipToResponse playerSkipTo(PlayerSkipToRequest request) {
        return playerSkipTo(request, Optional.empty());
    }

    /**
     * Player Skip To
     * 
     * <p>Skip to a specific item in the play queue.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSkipToResponse playerSkipTo(PlayerSkipToRequest request, Optional<Options> options) {
        RequestOperation<PlayerSkipToRequest, PlayerSkipToResponse> operation
              = new PlayerSkipTo.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Step Back
     * 
     * <p>Step back one frame
     * 
     * @return The call builder
     */
    public PlayerStepbackRequestBuilder playerStepback() {
        return new PlayerStepbackRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Step Back
     * 
     * <p>Step back one frame
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStepbackResponse playerStepback(PlayerStepbackRequest request) {
        return playerStepback(request, Optional.empty());
    }

    /**
     * Player Step Back
     * 
     * <p>Step back one frame
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStepbackResponse playerStepback(PlayerStepbackRequest request, Optional<Options> options) {
        RequestOperation<PlayerStepbackRequest, PlayerStepbackResponse> operation
              = new PlayerStepback.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Step Forward
     * 
     * <p>Step forward one frame
     * 
     * @return The call builder
     */
    public PlayerStepforwardRequestBuilder playerStepforward() {
        return new PlayerStepforwardRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Step Forward
     * 
     * <p>Step forward one frame
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStepforwardResponse playerStepforward(PlayerStepforwardRequest request) {
        return playerStepforward(request, Optional.empty());
    }

    /**
     * Player Step Forward
     * 
     * <p>Step forward one frame
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStepforwardResponse playerStepforward(PlayerStepforwardRequest request, Optional<Options> options) {
        RequestOperation<PlayerStepforwardRequest, PlayerStepforwardResponse> operation
              = new PlayerStepforward.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Stop
     * 
     * <p>Stop playback on the client
     * 
     * @return The call builder
     */
    public PlayerStopRequestBuilder playerStop() {
        return new PlayerStopRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Stop
     * 
     * <p>Stop playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStopResponse playerStop(PlayerStopRequest request) {
        return playerStop(request, Optional.empty());
    }

    /**
     * Player Stop
     * 
     * <p>Stop playback on the client
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerStopResponse playerStop(PlayerStopRequest request, Optional<Options> options) {
        RequestOperation<PlayerStopRequest, PlayerStopResponse> operation
              = new PlayerStop.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Subtitle Stream
     * 
     * <p>Change the active subtitle stream.
     * 
     * @return The call builder
     */
    public PlayerSubtitleStreamRequestBuilder playerSubtitleStream() {
        return new PlayerSubtitleStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Subtitle Stream
     * 
     * <p>Change the active subtitle stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSubtitleStreamResponse playerSubtitleStream(PlayerSubtitleStreamRequest request) {
        return playerSubtitleStream(request, Optional.empty());
    }

    /**
     * Player Subtitle Stream
     * 
     * <p>Change the active subtitle stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerSubtitleStreamResponse playerSubtitleStream(PlayerSubtitleStreamRequest request, Optional<Options> options) {
        RequestOperation<PlayerSubtitleStreamRequest, PlayerSubtitleStreamResponse> operation
              = new PlayerSubtitleStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Unmute
     * 
     * <p>Unmute the client audio
     * 
     * @return The call builder
     */
    public PlayerUnmuteRequestBuilder playerUnmute() {
        return new PlayerUnmuteRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Unmute
     * 
     * <p>Unmute the client audio
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerUnmuteResponse playerUnmute(PlayerUnmuteRequest request) {
        return playerUnmute(request, Optional.empty());
    }

    /**
     * Player Unmute
     * 
     * <p>Unmute the client audio
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerUnmuteResponse playerUnmute(PlayerUnmuteRequest request, Optional<Options> options) {
        RequestOperation<PlayerUnmuteRequest, PlayerUnmuteResponse> operation
              = new PlayerUnmute.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Video Stream
     * 
     * <p>Change the active video stream.
     * 
     * @return The call builder
     */
    public PlayerVideoStreamRequestBuilder playerVideoStream() {
        return new PlayerVideoStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Video Stream
     * 
     * <p>Change the active video stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerVideoStreamResponse playerVideoStream(PlayerVideoStreamRequest request) {
        return playerVideoStream(request, Optional.empty());
    }

    /**
     * Player Video Stream
     * 
     * <p>Change the active video stream.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerVideoStreamResponse playerVideoStream(PlayerVideoStreamRequest request, Optional<Options> options) {
        RequestOperation<PlayerVideoStreamRequest, PlayerVideoStreamResponse> operation
              = new PlayerVideoStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Volume
     * 
     * <p>Set the client volume.
     * 
     * @return The call builder
     */
    public PlayerVolumeRequestBuilder playerVolume() {
        return new PlayerVolumeRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Volume
     * 
     * <p>Set the client volume.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerVolumeResponse playerVolume(PlayerVolumeRequest request) {
        return playerVolume(request, Optional.empty());
    }

    /**
     * Player Volume
     * 
     * <p>Set the client volume.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerVolumeResponse playerVolume(PlayerVolumeRequest request, Optional<Options> options) {
        RequestOperation<PlayerVolumeRequest, PlayerVolumeResponse> operation
              = new PlayerVolume.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Client Resources
     * 
     * <p>Get client capabilities and device info.
     * 
     * @return The call builder
     */
    public GetClientResourcesRequestBuilder getClientResources() {
        return new GetClientResourcesRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Client Resources
     * 
     * <p>Get client capabilities and device info.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetClientResourcesResponse getClientResources(GetClientResourcesRequest request) {
        return getClientResources(request, Optional.empty());
    }

    /**
     * Get Client Resources
     * 
     * <p>Get client capabilities and device info.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetClientResourcesResponse getClientResources(GetClientResourcesRequest request, Optional<Options> options) {
        RequestOperation<GetClientResourcesRequest, GetClientResourcesResponse> operation
              = new GetClientResources.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Player Poll Timeline
     * 
     * <p>Poll the client for current playback timeline.
     * 
     * @return The call builder
     */
    public PlayerPollTimelineRequestBuilder playerPollTimeline() {
        return new PlayerPollTimelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Player Poll Timeline
     * 
     * <p>Poll the client for current playback timeline.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPollTimelineResponse playerPollTimeline(PlayerPollTimelineRequest request) {
        return playerPollTimeline(request, Optional.empty());
    }

    /**
     * Player Poll Timeline
     * 
     * <p>Poll the client for current playback timeline.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlayerPollTimelineResponse playerPollTimeline(PlayerPollTimelineRequest request, Optional<Options> options) {
        RequestOperation<PlayerPollTimelineRequest, PlayerPollTimelineResponse> operation
              = new PlayerPollTimeline.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
