/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.RequestlessOperation;
import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.models.operations.GetAllPreferencesRequestBuilder;
import dev.plexapi.sdk.models.operations.GetAllPreferencesResponse;
import dev.plexapi.sdk.models.operations.GetPreferenceRequest;
import dev.plexapi.sdk.models.operations.GetPreferenceRequestBuilder;
import dev.plexapi.sdk.models.operations.GetPreferenceResponse;
import dev.plexapi.sdk.models.operations.SetPreferencesRequest;
import dev.plexapi.sdk.models.operations.SetPreferencesRequestBuilder;
import dev.plexapi.sdk.models.operations.SetPreferencesResponse;
import dev.plexapi.sdk.operations.GetAllPreferences;
import dev.plexapi.sdk.operations.GetPreference;
import dev.plexapi.sdk.operations.SetPreferences;
import dev.plexapi.sdk.utils.Headers;
import dev.plexapi.sdk.utils.Options;
import java.util.Optional;

/**
 * API Operations against the Preferences
 */
public class Preferences {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncPreferences asyncSDK;

    Preferences(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncPreferences(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncPreferences async() {
        return asyncSDK;
    }

    /**
     * Get all preferences
     * 
     * <p>Get the list of all preferences
     * 
     * @return The call builder
     */
    public GetAllPreferencesRequestBuilder getAllPreferences() {
        return new GetAllPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Get all preferences
     * 
     * <p>Get the list of all preferences
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetAllPreferencesResponse getAllPreferencesDirect() {
        return getAllPreferences(Optional.empty());
    }

    /**
     * Get all preferences
     * 
     * <p>Get the list of all preferences
     * 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetAllPreferencesResponse getAllPreferences(Optional<Options> options) {
        RequestlessOperation<GetAllPreferencesResponse> operation
            = new GetAllPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Set preferences
     * 
     * <p>Set a set of preferences in query parameters
     * 
     * @return The call builder
     */
    public SetPreferencesRequestBuilder setPreferences() {
        return new SetPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Set preferences
     * 
     * <p>Set a set of preferences in query parameters
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SetPreferencesResponse setPreferences(SetPreferencesRequest request) {
        return setPreferences(request, Optional.empty());
    }

    /**
     * Set preferences
     * 
     * <p>Set a set of preferences in query parameters
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SetPreferencesResponse setPreferences(SetPreferencesRequest request, Optional<Options> options) {
        RequestOperation<SetPreferencesRequest, SetPreferencesResponse> operation
              = new SetPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a preferences
     * 
     * <p>Get a single preference and value
     * 
     * @return The call builder
     */
    public GetPreferenceRequestBuilder getPreference() {
        return new GetPreferenceRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a preferences
     * 
     * <p>Get a single preference and value
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetPreferenceResponse getPreference(GetPreferenceRequest request) {
        return getPreference(request, Optional.empty());
    }

    /**
     * Get a preferences
     * 
     * <p>Get a single preference and value
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetPreferenceResponse getPreference(GetPreferenceRequest request, Optional<Options> options) {
        RequestOperation<GetPreferenceRequest, GetPreferenceResponse> operation
              = new GetPreference.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
