/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.plexapi.sdk.utils.SpeakeasyMetadata;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class DiscoverDevicesRequest {
    /**
     * Protocol to filter discovery.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=protocol")
    private Optional<? extends Protocol> protocol;

    /**
     * Targeted grabber identifier.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=grabberIdentifier")
    private Optional<String> grabberIdentifier;

    @JsonCreator
    public DiscoverDevicesRequest(
            Optional<? extends Protocol> protocol,
            Optional<String> grabberIdentifier) {
        Utils.checkNotNull(protocol, "protocol");
        Utils.checkNotNull(grabberIdentifier, "grabberIdentifier");
        this.protocol = protocol;
        this.grabberIdentifier = grabberIdentifier;
    }
    
    public DiscoverDevicesRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Protocol to filter discovery.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Protocol> protocol() {
        return (Optional<Protocol>) protocol;
    }

    /**
     * Targeted grabber identifier.
     */
    @JsonIgnore
    public Optional<String> grabberIdentifier() {
        return grabberIdentifier;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Protocol to filter discovery.
     */
    public DiscoverDevicesRequest withProtocol(Protocol protocol) {
        Utils.checkNotNull(protocol, "protocol");
        this.protocol = Optional.ofNullable(protocol);
        return this;
    }


    /**
     * Protocol to filter discovery.
     */
    public DiscoverDevicesRequest withProtocol(Optional<? extends Protocol> protocol) {
        Utils.checkNotNull(protocol, "protocol");
        this.protocol = protocol;
        return this;
    }

    /**
     * Targeted grabber identifier.
     */
    public DiscoverDevicesRequest withGrabberIdentifier(String grabberIdentifier) {
        Utils.checkNotNull(grabberIdentifier, "grabberIdentifier");
        this.grabberIdentifier = Optional.ofNullable(grabberIdentifier);
        return this;
    }


    /**
     * Targeted grabber identifier.
     */
    public DiscoverDevicesRequest withGrabberIdentifier(Optional<String> grabberIdentifier) {
        Utils.checkNotNull(grabberIdentifier, "grabberIdentifier");
        this.grabberIdentifier = grabberIdentifier;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DiscoverDevicesRequest other = (DiscoverDevicesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.protocol, other.protocol) &&
            Utils.enhancedDeepEquals(this.grabberIdentifier, other.grabberIdentifier);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            protocol, grabberIdentifier);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DiscoverDevicesRequest.class,
                "protocol", protocol,
                "grabberIdentifier", grabberIdentifier);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends Protocol> protocol = Optional.empty();

        private Optional<String> grabberIdentifier = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Protocol to filter discovery.
         */
        public Builder protocol(Protocol protocol) {
            Utils.checkNotNull(protocol, "protocol");
            this.protocol = Optional.ofNullable(protocol);
            return this;
        }

        /**
         * Protocol to filter discovery.
         */
        public Builder protocol(Optional<? extends Protocol> protocol) {
            Utils.checkNotNull(protocol, "protocol");
            this.protocol = protocol;
            return this;
        }


        /**
         * Targeted grabber identifier.
         */
        public Builder grabberIdentifier(String grabberIdentifier) {
            Utils.checkNotNull(grabberIdentifier, "grabberIdentifier");
            this.grabberIdentifier = Optional.ofNullable(grabberIdentifier);
            return this;
        }

        /**
         * Targeted grabber identifier.
         */
        public Builder grabberIdentifier(Optional<String> grabberIdentifier) {
            Utils.checkNotNull(grabberIdentifier, "grabberIdentifier");
            this.grabberIdentifier = grabberIdentifier;
            return this;
        }

        public DiscoverDevicesRequest build() {

            return new DiscoverDevicesRequest(
                protocol, grabberIdentifier);
        }

    }
}
