/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * GetFriendsResponseBody
 * 
 * <p>List of friends
 */
public class GetFriendsResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("users")
    private Optional<? extends List<Users>> users;

    @JsonCreator
    public GetFriendsResponseBody(
            @JsonProperty("users") Optional<? extends List<Users>> users) {
        Utils.checkNotNull(users, "users");
        this.users = users;
    }
    
    public GetFriendsResponseBody() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Users>> users() {
        return (Optional<List<Users>>) users;
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetFriendsResponseBody withUsers(List<Users> users) {
        Utils.checkNotNull(users, "users");
        this.users = Optional.ofNullable(users);
        return this;
    }


    public GetFriendsResponseBody withUsers(Optional<? extends List<Users>> users) {
        Utils.checkNotNull(users, "users");
        this.users = users;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetFriendsResponseBody other = (GetFriendsResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.users, other.users);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            users);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetFriendsResponseBody.class,
                "users", users);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<Users>> users = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder users(List<Users> users) {
            Utils.checkNotNull(users, "users");
            this.users = Optional.ofNullable(users);
            return this;
        }

        public Builder users(Optional<? extends List<Users>> users) {
            Utils.checkNotNull(users, "users");
            this.users = users;
            return this;
        }

        public GetFriendsResponseBody build() {

            return new GetFriendsResponseBody(
                users);
        }

    }
}
