/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import dev.plexapi.sdk.models.shared.Accepts;
import dev.plexapi.sdk.utils.LazySingletonValue;
import dev.plexapi.sdk.utils.SpeakeasyMetadata;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class ListPlaybackHistoryRequest {
    /**
     * Indicates the client accepts the indicated media types
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=accepts")
    private Optional<? extends Accepts> accepts;

    /**
     * An opaque identifier unique to the client
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Client-Identifier")
    private Optional<String> clientIdentifier;

    /**
     * The name of the client product
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Product")
    private Optional<String> product;

    /**
     * The version of the client application
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Version")
    private Optional<String> version;

    /**
     * The platform of the client
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Platform")
    private Optional<String> platform;

    /**
     * The version of the platform
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Platform-Version")
    private Optional<String> platformVersion;

    /**
     * A relatively friendly name for the client device
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Device")
    private Optional<String> device;

    /**
     * A potentially less friendly identifier for the device model
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Model")
    private Optional<String> model;

    /**
     * The device vendor
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Device-Vendor")
    private Optional<String> deviceVendor;

    /**
     * A friendly name for the client
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Device-Name")
    private Optional<String> deviceName;

    /**
     * The marketplace on which the client application is distributed
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Plex-Marketplace")
    private Optional<String> marketplace;

    /**
     * Pagination start offset
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=X-Plex-Container-Start")
    private Optional<Long> xPlexContainerStart;

    /**
     * Pagination page size
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=X-Plex-Container-Size")
    private Optional<Long> xPlexContainerSize;

    /**
     * The account id to restrict view history
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=accountID")
    private Optional<Long> accountID;

    /**
     * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=viewedAt")
    private Optional<Long> viewedAt;

    /**
     * The library section id to restrict view history
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=librarySectionID")
    private Optional<Long> librarySectionID;

    /**
     * The metadata item to restrict view history (can provide the id for a show to see all of that show's
     * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
     * internally depending on the metadata type.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=metadataItemID")
    private Optional<Long> metadataItemID;

    /**
     * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
     * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
     * may not be used here.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")
    private Optional<? extends List<String>> sort;

    /**
     * Comma-separated list of elements to exclude from the response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=excludeElements")
    private Optional<String> excludeElements;

    /**
     * Comma-separated list of fields to exclude from the response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=excludeFields")
    private Optional<String> excludeFields;

    /**
     * Whitelist of fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=includeFields")
    private Optional<String> includeFields;

    /**
     * Whitelist of elements to include
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=includeElements")
    private Optional<String> includeElements;

    /**
     * Greater-than filter for viewedAt timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=viewedAt>")
    private Optional<Long> viewedAtGreaterThan;

    /**
     * Less-than filter for viewedAt timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=viewedAt<")
    private Optional<Long> viewedAtLessThan;

    /**
     * Filter by device ID
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=deviceID")
    private Optional<Long> deviceID;

    @JsonCreator
    public ListPlaybackHistoryRequest(
            Optional<? extends Accepts> accepts,
            Optional<String> clientIdentifier,
            Optional<String> product,
            Optional<String> version,
            Optional<String> platform,
            Optional<String> platformVersion,
            Optional<String> device,
            Optional<String> model,
            Optional<String> deviceVendor,
            Optional<String> deviceName,
            Optional<String> marketplace,
            Optional<Long> xPlexContainerStart,
            Optional<Long> xPlexContainerSize,
            Optional<Long> accountID,
            Optional<Long> viewedAt,
            Optional<Long> librarySectionID,
            Optional<Long> metadataItemID,
            Optional<? extends List<String>> sort,
            Optional<String> excludeElements,
            Optional<String> excludeFields,
            Optional<String> includeFields,
            Optional<String> includeElements,
            Optional<Long> viewedAtGreaterThan,
            Optional<Long> viewedAtLessThan,
            Optional<Long> deviceID) {
        Utils.checkNotNull(accepts, "accepts");
        Utils.checkNotNull(clientIdentifier, "clientIdentifier");
        Utils.checkNotNull(product, "product");
        Utils.checkNotNull(version, "version");
        Utils.checkNotNull(platform, "platform");
        Utils.checkNotNull(platformVersion, "platformVersion");
        Utils.checkNotNull(device, "device");
        Utils.checkNotNull(model, "model");
        Utils.checkNotNull(deviceVendor, "deviceVendor");
        Utils.checkNotNull(deviceName, "deviceName");
        Utils.checkNotNull(marketplace, "marketplace");
        Utils.checkNotNull(xPlexContainerStart, "xPlexContainerStart");
        Utils.checkNotNull(xPlexContainerSize, "xPlexContainerSize");
        Utils.checkNotNull(accountID, "accountID");
        Utils.checkNotNull(viewedAt, "viewedAt");
        Utils.checkNotNull(librarySectionID, "librarySectionID");
        Utils.checkNotNull(metadataItemID, "metadataItemID");
        Utils.checkNotNull(sort, "sort");
        Utils.checkNotNull(excludeElements, "excludeElements");
        Utils.checkNotNull(excludeFields, "excludeFields");
        Utils.checkNotNull(includeFields, "includeFields");
        Utils.checkNotNull(includeElements, "includeElements");
        Utils.checkNotNull(viewedAtGreaterThan, "viewedAtGreaterThan");
        Utils.checkNotNull(viewedAtLessThan, "viewedAtLessThan");
        Utils.checkNotNull(deviceID, "deviceID");
        this.accepts = accepts;
        this.clientIdentifier = clientIdentifier;
        this.product = product;
        this.version = version;
        this.platform = platform;
        this.platformVersion = platformVersion;
        this.device = device;
        this.model = model;
        this.deviceVendor = deviceVendor;
        this.deviceName = deviceName;
        this.marketplace = marketplace;
        this.xPlexContainerStart = xPlexContainerStart;
        this.xPlexContainerSize = xPlexContainerSize;
        this.accountID = accountID;
        this.viewedAt = viewedAt;
        this.librarySectionID = librarySectionID;
        this.metadataItemID = metadataItemID;
        this.sort = sort;
        this.excludeElements = excludeElements;
        this.excludeFields = excludeFields;
        this.includeFields = includeFields;
        this.includeElements = includeElements;
        this.viewedAtGreaterThan = viewedAtGreaterThan;
        this.viewedAtLessThan = viewedAtLessThan;
        this.deviceID = deviceID;
    }
    
    public ListPlaybackHistoryRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * Indicates the client accepts the indicated media types
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Accepts> accepts() {
        return (Optional<Accepts>) accepts;
    }

    /**
     * An opaque identifier unique to the client
     */
    @JsonIgnore
    public Optional<String> clientIdentifier() {
        return clientIdentifier;
    }

    /**
     * The name of the client product
     */
    @JsonIgnore
    public Optional<String> product() {
        return product;
    }

    /**
     * The version of the client application
     */
    @JsonIgnore
    public Optional<String> version() {
        return version;
    }

    /**
     * The platform of the client
     */
    @JsonIgnore
    public Optional<String> platform() {
        return platform;
    }

    /**
     * The version of the platform
     */
    @JsonIgnore
    public Optional<String> platformVersion() {
        return platformVersion;
    }

    /**
     * A relatively friendly name for the client device
     */
    @JsonIgnore
    public Optional<String> device() {
        return device;
    }

    /**
     * A potentially less friendly identifier for the device model
     */
    @JsonIgnore
    public Optional<String> model() {
        return model;
    }

    /**
     * The device vendor
     */
    @JsonIgnore
    public Optional<String> deviceVendor() {
        return deviceVendor;
    }

    /**
     * A friendly name for the client
     */
    @JsonIgnore
    public Optional<String> deviceName() {
        return deviceName;
    }

    /**
     * The marketplace on which the client application is distributed
     */
    @JsonIgnore
    public Optional<String> marketplace() {
        return marketplace;
    }

    /**
     * Pagination start offset
     */
    @JsonIgnore
    public Optional<Long> xPlexContainerStart() {
        return xPlexContainerStart;
    }

    /**
     * Pagination page size
     */
    @JsonIgnore
    public Optional<Long> xPlexContainerSize() {
        return xPlexContainerSize;
    }

    /**
     * The account id to restrict view history
     */
    @JsonIgnore
    public Optional<Long> accountID() {
        return accountID;
    }

    /**
     * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
     */
    @JsonIgnore
    public Optional<Long> viewedAt() {
        return viewedAt;
    }

    /**
     * The library section id to restrict view history
     */
    @JsonIgnore
    public Optional<Long> librarySectionID() {
        return librarySectionID;
    }

    /**
     * The metadata item to restrict view history (can provide the id for a show to see all of that show's
     * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
     * internally depending on the metadata type.
     */
    @JsonIgnore
    public Optional<Long> metadataItemID() {
        return metadataItemID;
    }

    /**
     * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
     * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
     * may not be used here.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> sort() {
        return (Optional<List<String>>) sort;
    }

    /**
     * Comma-separated list of elements to exclude from the response
     */
    @JsonIgnore
    public Optional<String> excludeElements() {
        return excludeElements;
    }

    /**
     * Comma-separated list of fields to exclude from the response
     */
    @JsonIgnore
    public Optional<String> excludeFields() {
        return excludeFields;
    }

    /**
     * Whitelist of fields to return
     */
    @JsonIgnore
    public Optional<String> includeFields() {
        return includeFields;
    }

    /**
     * Whitelist of elements to include
     */
    @JsonIgnore
    public Optional<String> includeElements() {
        return includeElements;
    }

    /**
     * Greater-than filter for viewedAt timestamp
     */
    @JsonIgnore
    public Optional<Long> viewedAtGreaterThan() {
        return viewedAtGreaterThan;
    }

    /**
     * Less-than filter for viewedAt timestamp
     */
    @JsonIgnore
    public Optional<Long> viewedAtLessThan() {
        return viewedAtLessThan;
    }

    /**
     * Filter by device ID
     */
    @JsonIgnore
    public Optional<Long> deviceID() {
        return deviceID;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Indicates the client accepts the indicated media types
     */
    public ListPlaybackHistoryRequest withAccepts(Accepts accepts) {
        Utils.checkNotNull(accepts, "accepts");
        this.accepts = Optional.ofNullable(accepts);
        return this;
    }


    /**
     * Indicates the client accepts the indicated media types
     */
    public ListPlaybackHistoryRequest withAccepts(Optional<? extends Accepts> accepts) {
        Utils.checkNotNull(accepts, "accepts");
        this.accepts = accepts;
        return this;
    }

    /**
     * An opaque identifier unique to the client
     */
    public ListPlaybackHistoryRequest withClientIdentifier(String clientIdentifier) {
        Utils.checkNotNull(clientIdentifier, "clientIdentifier");
        this.clientIdentifier = Optional.ofNullable(clientIdentifier);
        return this;
    }


    /**
     * An opaque identifier unique to the client
     */
    public ListPlaybackHistoryRequest withClientIdentifier(Optional<String> clientIdentifier) {
        Utils.checkNotNull(clientIdentifier, "clientIdentifier");
        this.clientIdentifier = clientIdentifier;
        return this;
    }

    /**
     * The name of the client product
     */
    public ListPlaybackHistoryRequest withProduct(String product) {
        Utils.checkNotNull(product, "product");
        this.product = Optional.ofNullable(product);
        return this;
    }


    /**
     * The name of the client product
     */
    public ListPlaybackHistoryRequest withProduct(Optional<String> product) {
        Utils.checkNotNull(product, "product");
        this.product = product;
        return this;
    }

    /**
     * The version of the client application
     */
    public ListPlaybackHistoryRequest withVersion(String version) {
        Utils.checkNotNull(version, "version");
        this.version = Optional.ofNullable(version);
        return this;
    }


    /**
     * The version of the client application
     */
    public ListPlaybackHistoryRequest withVersion(Optional<String> version) {
        Utils.checkNotNull(version, "version");
        this.version = version;
        return this;
    }

    /**
     * The platform of the client
     */
    public ListPlaybackHistoryRequest withPlatform(String platform) {
        Utils.checkNotNull(platform, "platform");
        this.platform = Optional.ofNullable(platform);
        return this;
    }


    /**
     * The platform of the client
     */
    public ListPlaybackHistoryRequest withPlatform(Optional<String> platform) {
        Utils.checkNotNull(platform, "platform");
        this.platform = platform;
        return this;
    }

    /**
     * The version of the platform
     */
    public ListPlaybackHistoryRequest withPlatformVersion(String platformVersion) {
        Utils.checkNotNull(platformVersion, "platformVersion");
        this.platformVersion = Optional.ofNullable(platformVersion);
        return this;
    }


    /**
     * The version of the platform
     */
    public ListPlaybackHistoryRequest withPlatformVersion(Optional<String> platformVersion) {
        Utils.checkNotNull(platformVersion, "platformVersion");
        this.platformVersion = platformVersion;
        return this;
    }

    /**
     * A relatively friendly name for the client device
     */
    public ListPlaybackHistoryRequest withDevice(String device) {
        Utils.checkNotNull(device, "device");
        this.device = Optional.ofNullable(device);
        return this;
    }


    /**
     * A relatively friendly name for the client device
     */
    public ListPlaybackHistoryRequest withDevice(Optional<String> device) {
        Utils.checkNotNull(device, "device");
        this.device = device;
        return this;
    }

    /**
     * A potentially less friendly identifier for the device model
     */
    public ListPlaybackHistoryRequest withModel(String model) {
        Utils.checkNotNull(model, "model");
        this.model = Optional.ofNullable(model);
        return this;
    }


    /**
     * A potentially less friendly identifier for the device model
     */
    public ListPlaybackHistoryRequest withModel(Optional<String> model) {
        Utils.checkNotNull(model, "model");
        this.model = model;
        return this;
    }

    /**
     * The device vendor
     */
    public ListPlaybackHistoryRequest withDeviceVendor(String deviceVendor) {
        Utils.checkNotNull(deviceVendor, "deviceVendor");
        this.deviceVendor = Optional.ofNullable(deviceVendor);
        return this;
    }


    /**
     * The device vendor
     */
    public ListPlaybackHistoryRequest withDeviceVendor(Optional<String> deviceVendor) {
        Utils.checkNotNull(deviceVendor, "deviceVendor");
        this.deviceVendor = deviceVendor;
        return this;
    }

    /**
     * A friendly name for the client
     */
    public ListPlaybackHistoryRequest withDeviceName(String deviceName) {
        Utils.checkNotNull(deviceName, "deviceName");
        this.deviceName = Optional.ofNullable(deviceName);
        return this;
    }


    /**
     * A friendly name for the client
     */
    public ListPlaybackHistoryRequest withDeviceName(Optional<String> deviceName) {
        Utils.checkNotNull(deviceName, "deviceName");
        this.deviceName = deviceName;
        return this;
    }

    /**
     * The marketplace on which the client application is distributed
     */
    public ListPlaybackHistoryRequest withMarketplace(String marketplace) {
        Utils.checkNotNull(marketplace, "marketplace");
        this.marketplace = Optional.ofNullable(marketplace);
        return this;
    }


    /**
     * The marketplace on which the client application is distributed
     */
    public ListPlaybackHistoryRequest withMarketplace(Optional<String> marketplace) {
        Utils.checkNotNull(marketplace, "marketplace");
        this.marketplace = marketplace;
        return this;
    }

    /**
     * Pagination start offset
     */
    public ListPlaybackHistoryRequest withXPlexContainerStart(long xPlexContainerStart) {
        Utils.checkNotNull(xPlexContainerStart, "xPlexContainerStart");
        this.xPlexContainerStart = Optional.ofNullable(xPlexContainerStart);
        return this;
    }


    /**
     * Pagination start offset
     */
    public ListPlaybackHistoryRequest withXPlexContainerStart(Optional<Long> xPlexContainerStart) {
        Utils.checkNotNull(xPlexContainerStart, "xPlexContainerStart");
        this.xPlexContainerStart = xPlexContainerStart;
        return this;
    }

    /**
     * Pagination page size
     */
    public ListPlaybackHistoryRequest withXPlexContainerSize(long xPlexContainerSize) {
        Utils.checkNotNull(xPlexContainerSize, "xPlexContainerSize");
        this.xPlexContainerSize = Optional.ofNullable(xPlexContainerSize);
        return this;
    }


    /**
     * Pagination page size
     */
    public ListPlaybackHistoryRequest withXPlexContainerSize(Optional<Long> xPlexContainerSize) {
        Utils.checkNotNull(xPlexContainerSize, "xPlexContainerSize");
        this.xPlexContainerSize = xPlexContainerSize;
        return this;
    }

    /**
     * The account id to restrict view history
     */
    public ListPlaybackHistoryRequest withAccountID(long accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = Optional.ofNullable(accountID);
        return this;
    }


    /**
     * The account id to restrict view history
     */
    public ListPlaybackHistoryRequest withAccountID(Optional<Long> accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    /**
     * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
     */
    public ListPlaybackHistoryRequest withViewedAt(long viewedAt) {
        Utils.checkNotNull(viewedAt, "viewedAt");
        this.viewedAt = Optional.ofNullable(viewedAt);
        return this;
    }


    /**
     * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
     */
    public ListPlaybackHistoryRequest withViewedAt(Optional<Long> viewedAt) {
        Utils.checkNotNull(viewedAt, "viewedAt");
        this.viewedAt = viewedAt;
        return this;
    }

    /**
     * The library section id to restrict view history
     */
    public ListPlaybackHistoryRequest withLibrarySectionID(long librarySectionID) {
        Utils.checkNotNull(librarySectionID, "librarySectionID");
        this.librarySectionID = Optional.ofNullable(librarySectionID);
        return this;
    }


    /**
     * The library section id to restrict view history
     */
    public ListPlaybackHistoryRequest withLibrarySectionID(Optional<Long> librarySectionID) {
        Utils.checkNotNull(librarySectionID, "librarySectionID");
        this.librarySectionID = librarySectionID;
        return this;
    }

    /**
     * The metadata item to restrict view history (can provide the id for a show to see all of that show's
     * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
     * internally depending on the metadata type.
     */
    public ListPlaybackHistoryRequest withMetadataItemID(long metadataItemID) {
        Utils.checkNotNull(metadataItemID, "metadataItemID");
        this.metadataItemID = Optional.ofNullable(metadataItemID);
        return this;
    }


    /**
     * The metadata item to restrict view history (can provide the id for a show to see all of that show's
     * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
     * internally depending on the metadata type.
     */
    public ListPlaybackHistoryRequest withMetadataItemID(Optional<Long> metadataItemID) {
        Utils.checkNotNull(metadataItemID, "metadataItemID");
        this.metadataItemID = metadataItemID;
        return this;
    }

    /**
     * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
     * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
     * may not be used here.
     */
    public ListPlaybackHistoryRequest withSort(List<String> sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = Optional.ofNullable(sort);
        return this;
    }


    /**
     * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
     * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
     * may not be used here.
     */
    public ListPlaybackHistoryRequest withSort(Optional<? extends List<String>> sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = sort;
        return this;
    }

    /**
     * Comma-separated list of elements to exclude from the response
     */
    public ListPlaybackHistoryRequest withExcludeElements(String excludeElements) {
        Utils.checkNotNull(excludeElements, "excludeElements");
        this.excludeElements = Optional.ofNullable(excludeElements);
        return this;
    }


    /**
     * Comma-separated list of elements to exclude from the response
     */
    public ListPlaybackHistoryRequest withExcludeElements(Optional<String> excludeElements) {
        Utils.checkNotNull(excludeElements, "excludeElements");
        this.excludeElements = excludeElements;
        return this;
    }

    /**
     * Comma-separated list of fields to exclude from the response
     */
    public ListPlaybackHistoryRequest withExcludeFields(String excludeFields) {
        Utils.checkNotNull(excludeFields, "excludeFields");
        this.excludeFields = Optional.ofNullable(excludeFields);
        return this;
    }


    /**
     * Comma-separated list of fields to exclude from the response
     */
    public ListPlaybackHistoryRequest withExcludeFields(Optional<String> excludeFields) {
        Utils.checkNotNull(excludeFields, "excludeFields");
        this.excludeFields = excludeFields;
        return this;
    }

    /**
     * Whitelist of fields to return
     */
    public ListPlaybackHistoryRequest withIncludeFields(String includeFields) {
        Utils.checkNotNull(includeFields, "includeFields");
        this.includeFields = Optional.ofNullable(includeFields);
        return this;
    }


    /**
     * Whitelist of fields to return
     */
    public ListPlaybackHistoryRequest withIncludeFields(Optional<String> includeFields) {
        Utils.checkNotNull(includeFields, "includeFields");
        this.includeFields = includeFields;
        return this;
    }

    /**
     * Whitelist of elements to include
     */
    public ListPlaybackHistoryRequest withIncludeElements(String includeElements) {
        Utils.checkNotNull(includeElements, "includeElements");
        this.includeElements = Optional.ofNullable(includeElements);
        return this;
    }


    /**
     * Whitelist of elements to include
     */
    public ListPlaybackHistoryRequest withIncludeElements(Optional<String> includeElements) {
        Utils.checkNotNull(includeElements, "includeElements");
        this.includeElements = includeElements;
        return this;
    }

    /**
     * Greater-than filter for viewedAt timestamp
     */
    public ListPlaybackHistoryRequest withViewedAtGreaterThan(long viewedAtGreaterThan) {
        Utils.checkNotNull(viewedAtGreaterThan, "viewedAtGreaterThan");
        this.viewedAtGreaterThan = Optional.ofNullable(viewedAtGreaterThan);
        return this;
    }


    /**
     * Greater-than filter for viewedAt timestamp
     */
    public ListPlaybackHistoryRequest withViewedAtGreaterThan(Optional<Long> viewedAtGreaterThan) {
        Utils.checkNotNull(viewedAtGreaterThan, "viewedAtGreaterThan");
        this.viewedAtGreaterThan = viewedAtGreaterThan;
        return this;
    }

    /**
     * Less-than filter for viewedAt timestamp
     */
    public ListPlaybackHistoryRequest withViewedAtLessThan(long viewedAtLessThan) {
        Utils.checkNotNull(viewedAtLessThan, "viewedAtLessThan");
        this.viewedAtLessThan = Optional.ofNullable(viewedAtLessThan);
        return this;
    }


    /**
     * Less-than filter for viewedAt timestamp
     */
    public ListPlaybackHistoryRequest withViewedAtLessThan(Optional<Long> viewedAtLessThan) {
        Utils.checkNotNull(viewedAtLessThan, "viewedAtLessThan");
        this.viewedAtLessThan = viewedAtLessThan;
        return this;
    }

    /**
     * Filter by device ID
     */
    public ListPlaybackHistoryRequest withDeviceID(long deviceID) {
        Utils.checkNotNull(deviceID, "deviceID");
        this.deviceID = Optional.ofNullable(deviceID);
        return this;
    }


    /**
     * Filter by device ID
     */
    public ListPlaybackHistoryRequest withDeviceID(Optional<Long> deviceID) {
        Utils.checkNotNull(deviceID, "deviceID");
        this.deviceID = deviceID;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListPlaybackHistoryRequest other = (ListPlaybackHistoryRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accepts, other.accepts) &&
            Utils.enhancedDeepEquals(this.clientIdentifier, other.clientIdentifier) &&
            Utils.enhancedDeepEquals(this.product, other.product) &&
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.platform, other.platform) &&
            Utils.enhancedDeepEquals(this.platformVersion, other.platformVersion) &&
            Utils.enhancedDeepEquals(this.device, other.device) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.deviceVendor, other.deviceVendor) &&
            Utils.enhancedDeepEquals(this.deviceName, other.deviceName) &&
            Utils.enhancedDeepEquals(this.marketplace, other.marketplace) &&
            Utils.enhancedDeepEquals(this.xPlexContainerStart, other.xPlexContainerStart) &&
            Utils.enhancedDeepEquals(this.xPlexContainerSize, other.xPlexContainerSize) &&
            Utils.enhancedDeepEquals(this.accountID, other.accountID) &&
            Utils.enhancedDeepEquals(this.viewedAt, other.viewedAt) &&
            Utils.enhancedDeepEquals(this.librarySectionID, other.librarySectionID) &&
            Utils.enhancedDeepEquals(this.metadataItemID, other.metadataItemID) &&
            Utils.enhancedDeepEquals(this.sort, other.sort) &&
            Utils.enhancedDeepEquals(this.excludeElements, other.excludeElements) &&
            Utils.enhancedDeepEquals(this.excludeFields, other.excludeFields) &&
            Utils.enhancedDeepEquals(this.includeFields, other.includeFields) &&
            Utils.enhancedDeepEquals(this.includeElements, other.includeElements) &&
            Utils.enhancedDeepEquals(this.viewedAtGreaterThan, other.viewedAtGreaterThan) &&
            Utils.enhancedDeepEquals(this.viewedAtLessThan, other.viewedAtLessThan) &&
            Utils.enhancedDeepEquals(this.deviceID, other.deviceID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accepts, clientIdentifier, product,
            version, platform, platformVersion,
            device, model, deviceVendor,
            deviceName, marketplace, xPlexContainerStart,
            xPlexContainerSize, accountID, viewedAt,
            librarySectionID, metadataItemID, sort,
            excludeElements, excludeFields, includeFields,
            includeElements, viewedAtGreaterThan, viewedAtLessThan,
            deviceID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListPlaybackHistoryRequest.class,
                "accepts", accepts,
                "clientIdentifier", clientIdentifier,
                "product", product,
                "version", version,
                "platform", platform,
                "platformVersion", platformVersion,
                "device", device,
                "model", model,
                "deviceVendor", deviceVendor,
                "deviceName", deviceName,
                "marketplace", marketplace,
                "xPlexContainerStart", xPlexContainerStart,
                "xPlexContainerSize", xPlexContainerSize,
                "accountID", accountID,
                "viewedAt", viewedAt,
                "librarySectionID", librarySectionID,
                "metadataItemID", metadataItemID,
                "sort", sort,
                "excludeElements", excludeElements,
                "excludeFields", excludeFields,
                "includeFields", includeFields,
                "includeElements", includeElements,
                "viewedAtGreaterThan", viewedAtGreaterThan,
                "viewedAtLessThan", viewedAtLessThan,
                "deviceID", deviceID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends Accepts> accepts;

        private Optional<String> clientIdentifier = Optional.empty();

        private Optional<String> product = Optional.empty();

        private Optional<String> version = Optional.empty();

        private Optional<String> platform = Optional.empty();

        private Optional<String> platformVersion = Optional.empty();

        private Optional<String> device = Optional.empty();

        private Optional<String> model = Optional.empty();

        private Optional<String> deviceVendor = Optional.empty();

        private Optional<String> deviceName = Optional.empty();

        private Optional<String> marketplace = Optional.empty();

        private Optional<Long> xPlexContainerStart = Optional.empty();

        private Optional<Long> xPlexContainerSize = Optional.empty();

        private Optional<Long> accountID = Optional.empty();

        private Optional<Long> viewedAt = Optional.empty();

        private Optional<Long> librarySectionID = Optional.empty();

        private Optional<Long> metadataItemID = Optional.empty();

        private Optional<? extends List<String>> sort = Optional.empty();

        private Optional<String> excludeElements = Optional.empty();

        private Optional<String> excludeFields = Optional.empty();

        private Optional<String> includeFields = Optional.empty();

        private Optional<String> includeElements = Optional.empty();

        private Optional<Long> viewedAtGreaterThan = Optional.empty();

        private Optional<Long> viewedAtLessThan = Optional.empty();

        private Optional<Long> deviceID = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Indicates the client accepts the indicated media types
         */
        public Builder accepts(Accepts accepts) {
            Utils.checkNotNull(accepts, "accepts");
            this.accepts = Optional.ofNullable(accepts);
            return this;
        }

        /**
         * Indicates the client accepts the indicated media types
         */
        public Builder accepts(Optional<? extends Accepts> accepts) {
            Utils.checkNotNull(accepts, "accepts");
            this.accepts = accepts;
            return this;
        }


        /**
         * An opaque identifier unique to the client
         */
        public Builder clientIdentifier(String clientIdentifier) {
            Utils.checkNotNull(clientIdentifier, "clientIdentifier");
            this.clientIdentifier = Optional.ofNullable(clientIdentifier);
            return this;
        }

        /**
         * An opaque identifier unique to the client
         */
        public Builder clientIdentifier(Optional<String> clientIdentifier) {
            Utils.checkNotNull(clientIdentifier, "clientIdentifier");
            this.clientIdentifier = clientIdentifier;
            return this;
        }


        /**
         * The name of the client product
         */
        public Builder product(String product) {
            Utils.checkNotNull(product, "product");
            this.product = Optional.ofNullable(product);
            return this;
        }

        /**
         * The name of the client product
         */
        public Builder product(Optional<String> product) {
            Utils.checkNotNull(product, "product");
            this.product = product;
            return this;
        }


        /**
         * The version of the client application
         */
        public Builder version(String version) {
            Utils.checkNotNull(version, "version");
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * The version of the client application
         */
        public Builder version(Optional<String> version) {
            Utils.checkNotNull(version, "version");
            this.version = version;
            return this;
        }


        /**
         * The platform of the client
         */
        public Builder platform(String platform) {
            Utils.checkNotNull(platform, "platform");
            this.platform = Optional.ofNullable(platform);
            return this;
        }

        /**
         * The platform of the client
         */
        public Builder platform(Optional<String> platform) {
            Utils.checkNotNull(platform, "platform");
            this.platform = platform;
            return this;
        }


        /**
         * The version of the platform
         */
        public Builder platformVersion(String platformVersion) {
            Utils.checkNotNull(platformVersion, "platformVersion");
            this.platformVersion = Optional.ofNullable(platformVersion);
            return this;
        }

        /**
         * The version of the platform
         */
        public Builder platformVersion(Optional<String> platformVersion) {
            Utils.checkNotNull(platformVersion, "platformVersion");
            this.platformVersion = platformVersion;
            return this;
        }


        /**
         * A relatively friendly name for the client device
         */
        public Builder device(String device) {
            Utils.checkNotNull(device, "device");
            this.device = Optional.ofNullable(device);
            return this;
        }

        /**
         * A relatively friendly name for the client device
         */
        public Builder device(Optional<String> device) {
            Utils.checkNotNull(device, "device");
            this.device = device;
            return this;
        }


        /**
         * A potentially less friendly identifier for the device model
         */
        public Builder model(String model) {
            Utils.checkNotNull(model, "model");
            this.model = Optional.ofNullable(model);
            return this;
        }

        /**
         * A potentially less friendly identifier for the device model
         */
        public Builder model(Optional<String> model) {
            Utils.checkNotNull(model, "model");
            this.model = model;
            return this;
        }


        /**
         * The device vendor
         */
        public Builder deviceVendor(String deviceVendor) {
            Utils.checkNotNull(deviceVendor, "deviceVendor");
            this.deviceVendor = Optional.ofNullable(deviceVendor);
            return this;
        }

        /**
         * The device vendor
         */
        public Builder deviceVendor(Optional<String> deviceVendor) {
            Utils.checkNotNull(deviceVendor, "deviceVendor");
            this.deviceVendor = deviceVendor;
            return this;
        }


        /**
         * A friendly name for the client
         */
        public Builder deviceName(String deviceName) {
            Utils.checkNotNull(deviceName, "deviceName");
            this.deviceName = Optional.ofNullable(deviceName);
            return this;
        }

        /**
         * A friendly name for the client
         */
        public Builder deviceName(Optional<String> deviceName) {
            Utils.checkNotNull(deviceName, "deviceName");
            this.deviceName = deviceName;
            return this;
        }


        /**
         * The marketplace on which the client application is distributed
         */
        public Builder marketplace(String marketplace) {
            Utils.checkNotNull(marketplace, "marketplace");
            this.marketplace = Optional.ofNullable(marketplace);
            return this;
        }

        /**
         * The marketplace on which the client application is distributed
         */
        public Builder marketplace(Optional<String> marketplace) {
            Utils.checkNotNull(marketplace, "marketplace");
            this.marketplace = marketplace;
            return this;
        }


        /**
         * Pagination start offset
         */
        public Builder xPlexContainerStart(long xPlexContainerStart) {
            Utils.checkNotNull(xPlexContainerStart, "xPlexContainerStart");
            this.xPlexContainerStart = Optional.ofNullable(xPlexContainerStart);
            return this;
        }

        /**
         * Pagination start offset
         */
        public Builder xPlexContainerStart(Optional<Long> xPlexContainerStart) {
            Utils.checkNotNull(xPlexContainerStart, "xPlexContainerStart");
            this.xPlexContainerStart = xPlexContainerStart;
            return this;
        }


        /**
         * Pagination page size
         */
        public Builder xPlexContainerSize(long xPlexContainerSize) {
            Utils.checkNotNull(xPlexContainerSize, "xPlexContainerSize");
            this.xPlexContainerSize = Optional.ofNullable(xPlexContainerSize);
            return this;
        }

        /**
         * Pagination page size
         */
        public Builder xPlexContainerSize(Optional<Long> xPlexContainerSize) {
            Utils.checkNotNull(xPlexContainerSize, "xPlexContainerSize");
            this.xPlexContainerSize = xPlexContainerSize;
            return this;
        }


        /**
         * The account id to restrict view history
         */
        public Builder accountID(long accountID) {
            Utils.checkNotNull(accountID, "accountID");
            this.accountID = Optional.ofNullable(accountID);
            return this;
        }

        /**
         * The account id to restrict view history
         */
        public Builder accountID(Optional<Long> accountID) {
            Utils.checkNotNull(accountID, "accountID");
            this.accountID = accountID;
            return this;
        }


        /**
         * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
         */
        public Builder viewedAt(long viewedAt) {
            Utils.checkNotNull(viewedAt, "viewedAt");
            this.viewedAt = Optional.ofNullable(viewedAt);
            return this;
        }

        /**
         * The time period to restrict history (typically of the form `viewedAt&gt;=12456789`)
         */
        public Builder viewedAt(Optional<Long> viewedAt) {
            Utils.checkNotNull(viewedAt, "viewedAt");
            this.viewedAt = viewedAt;
            return this;
        }


        /**
         * The library section id to restrict view history
         */
        public Builder librarySectionID(long librarySectionID) {
            Utils.checkNotNull(librarySectionID, "librarySectionID");
            this.librarySectionID = Optional.ofNullable(librarySectionID);
            return this;
        }

        /**
         * The library section id to restrict view history
         */
        public Builder librarySectionID(Optional<Long> librarySectionID) {
            Utils.checkNotNull(librarySectionID, "librarySectionID");
            this.librarySectionID = librarySectionID;
            return this;
        }


        /**
         * The metadata item to restrict view history (can provide the id for a show to see all of that show's
         * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
         * internally depending on the metadata type.
         */
        public Builder metadataItemID(long metadataItemID) {
            Utils.checkNotNull(metadataItemID, "metadataItemID");
            this.metadataItemID = Optional.ofNullable(metadataItemID);
            return this;
        }

        /**
         * The metadata item to restrict view history (can provide the id for a show to see all of that show's
         * view history). Note this is translated to `metadata_items.id`, `parents.id`, or `grandparents.id`
         * internally depending on the metadata type.
         */
        public Builder metadataItemID(Optional<Long> metadataItemID) {
            Utils.checkNotNull(metadataItemID, "metadataItemID");
            this.metadataItemID = metadataItemID;
            return this;
        }


        /**
         * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
         * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
         * may not be used here.
         */
        public Builder sort(List<String> sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = Optional.ofNullable(sort);
            return this;
        }

        /**
         * The field on which to sort. Multiple orderings can be specified separated by `,` and the direction
         * specified following a `:` (`desc` or `asc`; `asc` is assumed if not provided). Note `metadataItemID`
         * may not be used here.
         */
        public Builder sort(Optional<? extends List<String>> sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = sort;
            return this;
        }


        /**
         * Comma-separated list of elements to exclude from the response
         */
        public Builder excludeElements(String excludeElements) {
            Utils.checkNotNull(excludeElements, "excludeElements");
            this.excludeElements = Optional.ofNullable(excludeElements);
            return this;
        }

        /**
         * Comma-separated list of elements to exclude from the response
         */
        public Builder excludeElements(Optional<String> excludeElements) {
            Utils.checkNotNull(excludeElements, "excludeElements");
            this.excludeElements = excludeElements;
            return this;
        }


        /**
         * Comma-separated list of fields to exclude from the response
         */
        public Builder excludeFields(String excludeFields) {
            Utils.checkNotNull(excludeFields, "excludeFields");
            this.excludeFields = Optional.ofNullable(excludeFields);
            return this;
        }

        /**
         * Comma-separated list of fields to exclude from the response
         */
        public Builder excludeFields(Optional<String> excludeFields) {
            Utils.checkNotNull(excludeFields, "excludeFields");
            this.excludeFields = excludeFields;
            return this;
        }


        /**
         * Whitelist of fields to return
         */
        public Builder includeFields(String includeFields) {
            Utils.checkNotNull(includeFields, "includeFields");
            this.includeFields = Optional.ofNullable(includeFields);
            return this;
        }

        /**
         * Whitelist of fields to return
         */
        public Builder includeFields(Optional<String> includeFields) {
            Utils.checkNotNull(includeFields, "includeFields");
            this.includeFields = includeFields;
            return this;
        }


        /**
         * Whitelist of elements to include
         */
        public Builder includeElements(String includeElements) {
            Utils.checkNotNull(includeElements, "includeElements");
            this.includeElements = Optional.ofNullable(includeElements);
            return this;
        }

        /**
         * Whitelist of elements to include
         */
        public Builder includeElements(Optional<String> includeElements) {
            Utils.checkNotNull(includeElements, "includeElements");
            this.includeElements = includeElements;
            return this;
        }


        /**
         * Greater-than filter for viewedAt timestamp
         */
        public Builder viewedAtGreaterThan(long viewedAtGreaterThan) {
            Utils.checkNotNull(viewedAtGreaterThan, "viewedAtGreaterThan");
            this.viewedAtGreaterThan = Optional.ofNullable(viewedAtGreaterThan);
            return this;
        }

        /**
         * Greater-than filter for viewedAt timestamp
         */
        public Builder viewedAtGreaterThan(Optional<Long> viewedAtGreaterThan) {
            Utils.checkNotNull(viewedAtGreaterThan, "viewedAtGreaterThan");
            this.viewedAtGreaterThan = viewedAtGreaterThan;
            return this;
        }


        /**
         * Less-than filter for viewedAt timestamp
         */
        public Builder viewedAtLessThan(long viewedAtLessThan) {
            Utils.checkNotNull(viewedAtLessThan, "viewedAtLessThan");
            this.viewedAtLessThan = Optional.ofNullable(viewedAtLessThan);
            return this;
        }

        /**
         * Less-than filter for viewedAt timestamp
         */
        public Builder viewedAtLessThan(Optional<Long> viewedAtLessThan) {
            Utils.checkNotNull(viewedAtLessThan, "viewedAtLessThan");
            this.viewedAtLessThan = viewedAtLessThan;
            return this;
        }


        /**
         * Filter by device ID
         */
        public Builder deviceID(long deviceID) {
            Utils.checkNotNull(deviceID, "deviceID");
            this.deviceID = Optional.ofNullable(deviceID);
            return this;
        }

        /**
         * Filter by device ID
         */
        public Builder deviceID(Optional<Long> deviceID) {
            Utils.checkNotNull(deviceID, "deviceID");
            this.deviceID = deviceID;
            return this;
        }

        public ListPlaybackHistoryRequest build() {
            if (accepts == null) {
                accepts = _SINGLETON_VALUE_Accepts.value();
            }

            return new ListPlaybackHistoryRequest(
                accepts, clientIdentifier, product,
                version, platform, platformVersion,
                device, model, deviceVendor,
                deviceName, marketplace, xPlexContainerStart,
                xPlexContainerSize, accountID, viewedAt,
                librarySectionID, metadataItemID, sort,
                excludeElements, excludeFields, includeFields,
                includeElements, viewedAtGreaterThan, viewedAtLessThan,
                deviceID);
        }


        private static final LazySingletonValue<Optional<? extends Accepts>> _SINGLETON_VALUE_Accepts =
                new LazySingletonValue<>(
                        "accepts",
                        "\"application/xml\"",
                        new TypeReference<Optional<? extends Accepts>>() {});
    }
}
