/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class PostUsersSignInDataState {

    public static final PostUsersSignInDataState ENDED = new PostUsersSignInDataState("ended");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PostUsersSignInDataState> values = createValuesMap();
    private static final Map<String, PostUsersSignInDataStateEnum> enums = createEnumsMap();

    private final String value;

    private PostUsersSignInDataState(String value) {
        this.value = value;
    }

    /**
     * Returns a PostUsersSignInDataState with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PostUsersSignInDataState
     */ 
    @JsonCreator
    public static PostUsersSignInDataState of(String value) {
        synchronized (PostUsersSignInDataState.class) {
            return values.computeIfAbsent(value, v -> new PostUsersSignInDataState(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PostUsersSignInDataStateEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PostUsersSignInDataState other = (PostUsersSignInDataState) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PostUsersSignInDataState [value=" + value + "]";
    }

    // return an array just like an enum
    public static PostUsersSignInDataState[] values() {
        synchronized (PostUsersSignInDataState.class) {
            return values.values().toArray(new PostUsersSignInDataState[] {});
        }
    }

    private static final Map<String, PostUsersSignInDataState> createValuesMap() {
        Map<String, PostUsersSignInDataState> map = new LinkedHashMap<>();
        map.put("ended", ENDED);
        return map;
    }

    private static final Map<String, PostUsersSignInDataStateEnum> createEnumsMap() {
        Map<String, PostUsersSignInDataStateEnum> map = new HashMap<>();
        map.put("ended", PostUsersSignInDataStateEnum.ENDED);
        return map;
    }
    
    
    public enum PostUsersSignInDataStateEnum {

        ENDED("ended"),;

        private final String value;

        private PostUsersSignInDataStateEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

