/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PostUsersSignInDataAuthenticationStatus
 * 
 * <p>String representation of subscriptionActive
 */
public class PostUsersSignInDataAuthenticationStatus {

    public static final PostUsersSignInDataAuthenticationStatus INACTIVE = new PostUsersSignInDataAuthenticationStatus("Inactive");
    public static final PostUsersSignInDataAuthenticationStatus ACTIVE = new PostUsersSignInDataAuthenticationStatus("Active");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PostUsersSignInDataAuthenticationStatus> values = createValuesMap();
    private static final Map<String, PostUsersSignInDataAuthenticationStatusEnum> enums = createEnumsMap();

    private final String value;

    private PostUsersSignInDataAuthenticationStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a PostUsersSignInDataAuthenticationStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PostUsersSignInDataAuthenticationStatus
     */ 
    @JsonCreator
    public static PostUsersSignInDataAuthenticationStatus of(String value) {
        synchronized (PostUsersSignInDataAuthenticationStatus.class) {
            return values.computeIfAbsent(value, v -> new PostUsersSignInDataAuthenticationStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PostUsersSignInDataAuthenticationStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PostUsersSignInDataAuthenticationStatus other = (PostUsersSignInDataAuthenticationStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PostUsersSignInDataAuthenticationStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static PostUsersSignInDataAuthenticationStatus[] values() {
        synchronized (PostUsersSignInDataAuthenticationStatus.class) {
            return values.values().toArray(new PostUsersSignInDataAuthenticationStatus[] {});
        }
    }

    private static final Map<String, PostUsersSignInDataAuthenticationStatus> createValuesMap() {
        Map<String, PostUsersSignInDataAuthenticationStatus> map = new LinkedHashMap<>();
        map.put("Inactive", INACTIVE);
        map.put("Active", ACTIVE);
        return map;
    }

    private static final Map<String, PostUsersSignInDataAuthenticationStatusEnum> createEnumsMap() {
        Map<String, PostUsersSignInDataAuthenticationStatusEnum> map = new HashMap<>();
        map.put("Inactive", PostUsersSignInDataAuthenticationStatusEnum.INACTIVE);
        map.put("Active", PostUsersSignInDataAuthenticationStatusEnum.ACTIVE);
        return map;
    }
    
    
    public enum PostUsersSignInDataAuthenticationStatusEnum {

        INACTIVE("Inactive"),
        ACTIVE("Active"),;

        private final String value;

        private PostUsersSignInDataAuthenticationStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

